### ISSUE TITLE
Missing endpoint for creating a service dialog from a ConfigurationTemplate

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#1007]
Ansible Tower Configuration Templates allow the creation of service dialogs from themselves via the UI. This feature should be also implemented via an API action to be able to [convert the form to DDF](https://github.com/ManageIQ/manageiq-ui-classic/issues/6899).

@miq-bot add_label help wanted
@miq-bot assign @gtanzillo

**Comment by lfu** [comment]
It's already done in https://github.com/ManageIQ/manageiq-api/pull/616.

**Comment by Fryguy** [comment]
Closed via #616
