### ISSUE TITLE
[RFE] Allow querying provider types by supports_* attributes

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-api#1034]
Use case:
Query for provider class names which `support_object_storage` so that they can be filtered for dialogs.

Suggestion:
Add filtering support to provider options, e.g. `OPTIONS /api/providers?filter[]=supports_object_storage`

Required for:
* https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/159

**Comment by agrare** [comment]
cc @Fryguy @bdunne

**Comment by agrare** [comment]
This is needed to identify Object versus Block storage managers.  AFAIK these are the only type of manager which we show on the UI separately but are actually the same manager type, with mixins bringing the Object and/or Block traits.

I'm assuming this was done so that a single storage manager which implements both would be able to be supported, but it is unique among the rest of the providers.

I'm not sure if the right answer here is to
1. Implement this API call so the UI can show only block/object storage managers in the respective create forms
2. Change the UI to show a "unified" storage manager create page where any standalone storage manager could be created (this makes more sense if we consider a hypothetical storage manager that supports both object and block types)
3. Ditch the whole single StorageManager with object/block mixins idea and go to StorageManager::ObjectManager/BlockManager sublasses.

**Comment by Fryguy** [comment]
Offhand, I like 3, cause it makes things consistent - not sure if this complicates other flows though, 2 seems like a better tactical fix.  Let's discuss.

**Comment by agrare** [comment]
Oh forgot one more option
4. Allow both Object and Block traits in the base StorageManager - essentially include associations for both in the base StorageManager and let the providers indicate via `supports?()` what is implemented.  This would allow to still support a provider which implements both types

**Comment by iv1111** [comment]
One thing I thought about. If I'm not wrong, there is no scenario where a given Storage provider would include **both** Object- and Block Mixins. In that case, current arch. is basically equivalent to having two different providers, only instead of inheritance the corresp. mixins are used.

**Comment by agrare** [comment]
@iv1111 That's correct, but the current design clearly was done this way to allow that.  We need to decide if we want to continue that or decide it doesn't matter.

**Comment by agrare** [comment]
Yeah option 4 is what https://github.com/ManageIQ/manageiq/pull/21213 is doing now, basically moved the associations from the Object and Block Mixins into the base StorageManager class and allowing the child providers to say `supports :block_storage` and/or `supports :object_storage`.

**Comment by Fryguy** [comment]
+1 for option 4

**Comment by kavyanekkalapu** [comment]
> Yeah option 4 is what [ManageIQ/manageiq#21213](https://github.com/ManageIQ/manageiq/pull/21213) is doing now, basically moved the associations from the Object and Block Mixins into the base StorageManager class and allowing the child providers to say `supports :block_storage` and/or `supports :object_storage`.

@agrare @Fryguy currently, block storage just using existing create providers page. Now option 4 means, in UI we need separate api calls/components for create block storage and create object storage?

**Comment by agrare** [comment]
Hey @kavyanekkalapu this way there will be only one "Add Storage Manager", should be able to just reuse the existing add block storage component since that just works on the "Storage" type currently

**Comment by agrare** [comment]
The biggest difference I think will be currently the UI has separate sections for block and object storage.  We'll need to either combine these into one or have a separate menu item for adding new storage managers.

**Comment by agrare** [comment]
Okay I'm going to close this in favor of https://github.com/ManageIQ/manageiq/pull/21213 since we all seem to be in agreement on that approach
