### ISSUE TITLE
DDF schema parameters are not getting translated in api response.

### ISSUE THREAD

**Issue by kavyanekkalapu** [ManageIQ/manageiq-api#1042]
**Issue:** When user switches to any other language other than English, wherever UI calling backend from ddf schema, those strings/labels are not coming back as  translated strings.

Sample api call: http://localhost:3000/api/providers?type=ManageIQ::Providers::Openstack::CloudManager, you can see UI for this call in Compute--> Clouds--> Add New Provider
 
<img width="910" alt="Screen Shot 2021-06-03 at 2 33 48 PM" src="https://user-images.githubusercontent.com/37085529/120694935-c11db000-c478-11eb-8008-eb32eddcdda0.png">

@miq-bot add-label bug
@miq-bot assign @NickLaMuro 
@miq-bot assign @Fryguy

**Comment by kavyanekkalapu** [comment]
I am able to assign it to only one person CC @NickLaMuro

**Comment by NickLaMuro** [comment]
@kavyanekkalapu Thanks, I cheated and used "super powers" to add myself.  Probably something we can fix with the bot, but this approach works for now.

I can take a look at this later today then, since it is blocking your team.

**Comment by kavyanekkalapu** [comment]
> @kavyanekkalapu Thanks, I cheated and used "super powers" to add myself. Probably something we can fix with the bot, but this approach works for now.
> 
> I can take a look at this later today then, since it is blocking your team.

Thank you very much, this affects every form which is loading ddf schema from backend/api, if we can fix this, this will close many issues.

**Comment by NickLaMuro** [comment]
Cool.  I don't see this as being too difficult (compared to other things), so I can't see why it won't take long to provide a fix.

**Comment by NickLaMuro** [comment]
@kavyanekkalapu I think this PR should mostly address things for you:

https://github.com/ManageIQ/manageiq-api/pull/1043

There are still cases that need to be addressed as well, but this should be at least make sure the places that are properly configured to be translated are.

**Comment by NickLaMuro** [comment]
Going to close this as I think this was addressed in #1043 .  Please re-open if there are further issues that need to be addressed.
