### ISSUE TITLE
http POST method turns into http GET on Kasparov-1

### ISSUE THREAD

**Issue by rashidramk** [ManageIQ/manageiq-api#1049]
When I call a POST API request using postman, and see manageiq api log, the requests turns into GET type on Kasparov-1 and it is working fine on ivanchuk.  I'm testing on http, could be it due to http instead of HTTPS?

**Comment by NickLaMuro** [comment]
@rashidramk can you provide some form of example request that you are doing for this?  I wasn't able reproduce on `master`, so I am curious if this is something specific with `kasparov-1`, or if I am just not doing things properly.

**Comment by rashidramk** [comment]
I figured it out. I was running my IP on HTTP and it caused the issue. Now I'm running it on HTTPS and every thing works fine. Thanks.
