### ISSUE TITLE
vm_reconfigure request has no effect on vm params

### ISSUE THREAD

**Issue by szajac01** [ManageIQ/manageiq-api#1104]
The request API (https://{{hostname}}/api/requests) should provide availability to reconfigure VM fields
I did try with those POST, request is created, successfully finished, but VM memory does not change,

`{  
   "action":"create",
   "options":{  
      "src_ids":[  
         "1749"
      ],
      "request_type":"vm_reconfigure",
      "vm_fields":[
          {
            "vm_memory": "8192"
          }
      ]
   },
   "auto_approve":true
}`

Same with a change CPU, i did try a lot of tests , no changes on cpu

`{  
   "action":"create",
   "options":{  
      "src_ids":[  
         "3010"
      ],
      "request_type":"vm_reconfigure",
      "hardware":[
          {
            "number_of_sockets": "2",
            "cores_per_socket": "4"
          }
      ]
   },
   "auto_approve":true
}`

Also adding a disk does work with this post
`{  
   "action":"create",
   "options":{  
      "src_ids":[  
         "3010"
      ],
      "request_type":"vm_reconfigure",
      "disk_add":[  
         {  
            "disk_size_in_mb":"4096",
            "persistent":true,
            "thin_provisioned":true,
            "dependent":true,
            "bootable":false
         }
      ]
   },
   "auto_approve":true
}`

is it a misunderstood or a known bug.
When you reconfigure with the UI feature, that works fine.
We need to find a solution with API to be called by an external workflow.

**Comment by szajac01** [comment]
mention it's on tested on  kasparov1 and kasparov2

**Comment by agrare** [comment]
Thanks for the bug report @szajac01, is provider was this VM on?  Can you tell from the logs if the request ran at all?  If so did it fail?

**Comment by szajac01** [comment]
Hi @agrare , provider is VMware.
From the API response, the request run and finish in successful state .
_`"request_type": "vm_reconfigure",
    "request_state": "finished",
    "message": "VM Reconfigure complete",
    "status": "Ok",`_

from automation.log, also no error, i can share with you logs if needed

**Comment by szajac01** [comment]
Hi guys, any news on the subject ?
did you reproduce issue ? Is there any workaround ?

**Comment by agrare** [comment]
Hey @szajac01 sorry for the delay I am investigating this issues now.  When I used the payload that you provided, specifically `"vm_fields":[ { "vm_memory": "8192" } ]` I ended up with a reconfig spec that was empty.

It appears that the correct payload would be:
`{ "action":"create", "options":{ "src_ids":[ "2" ], "request_type":"vm_reconfigure", "vm_memory": "8192" }, "auto_approve":true }`

That would be the same for the CPU options as well (`"cores_per_socket"` and `"number_of_cpus"`)

**Comment by agrare** [comment]
Where did you see the `"vm_fields"` style?  I want to make sure to correct any documentation that is inaccurate.  I also don't see any API examples in the docs of reconfigure so I'll add one

**Comment by agrare** [comment]
I see vm_fields comes from the miq_provision request, this isn't the same for reconfigure.

@szajac01 See https://www.manageiq.org/docs/reference/latest/api/examples/reconfigure_vm.html for examples of VM reconfigure requests

**Comment by szajac01** [comment]
Hi @agrare, you're right thanks.
I still have a problem regarding adding cpu

with this request
`{  
   "action":"create",
   "options":{  
      "src_ids":[  
         "3591"
      ],
      "request_type":"vm_reconfigure",
      "number_of_sockets": "2",
      "cores_per_socket": "4"
   },
   "auto_approve":true
}`
_Error: The attempted operation cannot be performed in the current state (Powered on)._
even if hot add is enabled... "cpu_hot_add_enabled"=>true
it works on the VMware side.

with this request
`{  
   "action":"create",
   "options":{  
      "src_ids":[  
         "3591"
      ],
      "request_type":"vm_reconfigure",
      "number_of_cpus": "8"
   },
   "auto_approve":true
}
`

_Error: Error: Cannot change CPU cores per socket on a running VM_
