### ISSUE TITLE
Template API Issue with child_resources

### ISSUE THREAD

**Issue by GilbertCherrie** [ManageIQ/manageiq-api#1117]
When trying to edit a template using the edit API call to a /api/templates/{recordId} it returns an error:

<img width="1129" alt="Error" src="https://user-images.githubusercontent.com/32444791/149977422-7c1c3a33-8555-468c-b2da-df63c9b3e1e3.png">

Data being sent in API call:
<img width="305" alt="Screen Shot 2022-01-18 at 11 26 56 AM" src="https://user-images.githubusercontent.com/32444791/149977522-f37303df-d3df-4830-a025-c4baf9825507.png">

This same call works for /api/vms/ but not templates.

**Comment by Fryguy** [comment]
So, as discussed, the templates controller doesn't accept the parent_resource and child_resources, but I also didn't think it should blow up, since the templates controller explicitly removes everything except name and description.  Do you have a stack trace?

**Comment by Fryguy** [comment]
@kbrock Can you help @GilbertCherrie here?  it's almost like the values aren't being removed?

**Comment by GilbertCherrie** [comment]
@Fryguy I guess I wasn't too clear but on my local API code I changed the code so that it doesn't remove any values. This error is the result of that. I just thought the edit should still work even if all the logic is missing in the api code for the parent and children.

**Comment by GilbertCherrie** [comment]
I fixed the issue and will get a PR out. After reviewing the vm controller file it turns out the vm is not actually sending in the parent and child resources to the update call. These are only used in different functions that set the parent and child relationships. So after adding in the logic from the vm controller file, the template controller file seems to be fixed now.
