### ISSUE TITLE
When no current_user defined exception raised

### ISSUE THREAD

**Issue by mkanoor** [ManageIQ/manageiq-api#12]
When logging in for the first time, there is no User.current_user set and the log_request line blows up with the exception
#<NoMethodError: undefined method `userid' for nil:NilClass>

Which leads to the render being called multiple times

 https://github.com/ManageIQ/manageiq-api/blob/33eb2d8780e9e9f3464adec6c032c54e21fb3560/app/controllers/api/base_controller.rb#L35

F, [2017-08-09T14:23:54.647550 #4476] FATAL -- : AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):

**Comment by abellotti** [comment]
we do set the User.current_user in the base_controller/authentication.rb for the authenticated user.  Is this a logging issue only   ?  i.e. we're trying to log the userid but haven't created the user object yet ?

**Comment by mkanoor** [comment]
@abellotti This the first time thru the user has never logged in and we have not displayed the Dialog to the User to collect the userid/password. So User.current_user is not set

**Comment by mkanoor** [comment]
@abellotti 
   https://github.com/ManageIQ/manageiq-api/blob/33eb2d8780e9e9f3464adec6c032c54e21fb3560/app/controllers/api/base_controller/logger.rb#L21 is the line that logs this message.

https://github.com/ManageIQ/manageiq-api/blob/33eb2d8780e9e9f3464adec6c032c54e21fb3560/app/controllers/api/base_controller/logger.rb#L25 does protect against User.current_user being nil but the log line doesn't

**Comment by mkanoor** [comment]
@jrafanie I think you ran into the same issue.

**Comment by jrafanie** [comment]
Yeah, I think I ran into this @mkanoor.  My workaround when running `bin/rails s` after initial seeding was to log into the classic ui and then I could hit `/api` in the browser.
