### ISSUE TITLE
Fill out README

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/manageiq-api#120]
Doesn't give a description, says it's on RubyGems even though it's not, etc. Should update all this to make things clear to project newcomers.

**Comment by Fryguy** [comment]
*all* of the new plugins are like this.  Someone (not me 😛 ) should probably go through each one and update it.  Maybe we can collaborate on some common set of base documentation?

**Comment by chrisarcand** [comment]
You'll be finding a _lot_ of 'Oh yeah, all the plugins do this too' issues I'm reporting and fixing here in the API ^_^
