### ISSUE TITLE
Can't create a user for multiple groups 

### ISSUE THREAD

**Issue by GilbertCherrie** [ManageIQ/manageiq-api#1238]
As described in the docs: https://www.manageiq.org/docs/reference/latest/api/reference/users.html#creating-users I tried to crate a user using the API. The current Add user page allows for users to be created as part of multiple groups but there does not seem to be any way to do this with the API according to the documentation. When trying to pass in multiple groups using an array I hit the error:
![Screenshot 2023-08-30 at 3 46 45 PM](https://github.com/ManageIQ/manageiq-api/assets/32444791/4c15306f-8772-4bc8-b0a6-83f4d29e1cd1)

This error was hit with the payload:
![Screenshot 2023-08-30 at 4 57 09 PM](https://github.com/ManageIQ/manageiq-api/assets/32444791/9f9d140d-02fa-44b8-bb8b-7c18913fe4d7)

**Comment by GilbertCherrie** [comment]
@miq-bot add-label bug

**Comment by Fryguy** [comment]
When this gets worked on we have to make sure we distinguish current group from "all groups.  I wonder if this just needs subcollection support.

**Comment by Fryguy** [comment]
@kbrock Can you add some comments here on what you've found.

**Comment by kbrock** [comment]
I see specs for creating it:
https://github.com/ManageIQ/manageiq-api/blob/master/spec/requests/users_spec.rb#L234-L251

**Comment by GilbertCherrie** [comment]
@kbrock It looks like the POST call to add/edit is working in terms of adding a user to multiple groups. However I think the GET call to get a user data is broken because when trying to call GET on a specific user id it returns only the current group not all the groups the user is in. This is the summary page showing all 5 groups that I selected on the add/edit page showing that it is POSTing the data correctly.
<img width="1149" alt="Screenshot 2023-09-28 at 11 22 31 AM" src="https://github.com/ManageIQ/manageiq-api/assets/32444791/aba44646-0b42-4e26-8e74-ec28dfa22332">

However this is what the API GET call returns for the same user:
<img width="524" alt="Screenshot 2023-09-28 at 11 22 17 AM" src="https://github.com/ManageIQ/manageiq-api/assets/32444791/53a33cd4-fbaf-4970-891f-1fb39ecfbdf1">

**Comment by kbrock** [comment]
@GilbertCherrie you can get the groups by passing the parameter: `:attributes => "miq_groups"`.

I ensured it worked with both an individual user and a collection of users.

**Comment by GilbertCherrie** [comment]
Closing this issue as fixed since @kbrock's solution of passing `:attributes => "miq_groups"` fixed the issue.
