### ISSUE TITLE
Rein in message passing to `Object` in collection config

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/manageiq-api#134]
https://github.com/ManageIQ/manageiq-api/blob/c5cc04a2ae95b8ac89436ceb25b774f41eff1a58/lib/api/collection_config.rb#L7-L13

As brought up on Gitter by @himdel, we should rein in how we handle the issue fixed by this rescue. We're currently still sending the message (calling the method) unrestricted on the config object, so you can send things like `display` (which writes to stdout), etc. That's less than ideal.

At the very least, if this is indeed the best solution, I wonder what error is being rescued here.

**Comment by himdel** [comment]
Traceback of the case where this makes the API output a lot of stuff on any /api access :+1: 

```
 "/home/milan/.rbenv/versions/2.4.1/lib/ruby/2.4.0/ostruct.rb:281:in `inspect'",
 "/home/milan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/config-1.3.0/lib/config/options.rb:135:in `write'",
 "/home/milan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/config-1.3.0/lib/config/options.rb:135:in `display'",
 "/home/milan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/config-1.3.0/lib/config/options.rb:135:in `[]'",
 "/home/milan/src/manage-iq/manageiq-api/lib/api/collection_config.rb:10:in `[]'",
 "/home/milan/src/manage-iq/manageiq-api/lib/api/collection_config.rb:98:in `resource_identifier'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:14:in `normalize_hash'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:35:in `normalize_attr'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:22:in `block in normalize_hash'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:21:in `each'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:21:in `normalize_hash'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:35:in `normalize_attr'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:22:in `block in normalize_hash'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:21:in `each'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:21:in `normalize_hash'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:35:in `normalize_attr'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:22:in `block in normalize_hash'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:21:in `each'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/normalizer.rb:21:in `normalize_hash'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/renderer.rb:79:in `resource_to_jbuilder'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/base_controller/renderer.rb:17:in `render_resource'",
 "/home/milan/src/manage-iq/manageiq-api/app/controllers/api/api_controller.rb:20:in `index'",
```

**Comment by abellotti** [comment]
ping @jntullo, the outstanding issue we have with the normalizer where the recursion is not calling normalize_hash with the type _might_ be the reason why these exceptions are happening in collection config []  in the first place. Can you take a look ?  in which case with your fix we could actually remove the above rescue.  Thanks.

**Comment by jntullo** [comment]
@abellotti I did investigate this, and for the cases that I saw, the type *is* being passed in, because it is the name of the attribute. Did you have a more specific case that I could take a look at?

**Comment by abellotti** [comment]
remove that rescue and run the automate_specs rspecs, you'll see that exception in action.

**Comment by imtayadeway** [comment]
@chrisarcand @himdel I think the discussion in https://github.com/ManageIQ/manageiq-api/pull/83#discussion_r142692900 is relevant in here. My proposal is if we merge https://github.com/ManageIQ/manageiq/pull/16138 we can go ahead and remove the calling code that is causing us to send all these messages to `Config::Options` and only send it sane things i.e. things that we have a reasonable expectation of returning something meaningful.

**Comment by himdel** [comment]
IMO the problem is a bit further away:

By using `Config::Options` instead of something else, we're arbitrarily limiting the names of allowed keys in the config. Furthermore, we're not limiting it to a set that's under our control, we're limitting it to a set determined by the ruby standard library and a couple of gems.

That sounds like a recipe for disaster for *any* use :).

(Unless I'm missing something?)

**Comment by chrisarcand** [comment]
As I mentioned in the blacklist PR, replacing that gem is very likely *not* trivial unless @Fryguy can give some other insight. A solution such as the blacklist or what @imtayadeway is describing seems appropriate for now (and perhaps permanently)

**Comment by Fryguy** [comment]
Yeah, it's non-trivial to replace that gem.  config gem has an [internal blacklist](https://github.com/railsconfig/config/blob/master/lib/config/options.rb#L136-L137), and they are pretty good about [accepting PRs to update it](https://github.com/railsconfig/config/pull/167).  I could also see having our *own* blacklist in Vmdb::Settings, which is easier to update in a pinch, and then we can add some kind of spec that ensures that people don't add keys to the config that are blacklisted.

**Comment by Fryguy** [comment]
I *thought* I had an open issue for this, but one of my "future plans" with settings.yml is to have some kind of validation on it, so that people touching Advanced Settings can't break the system.  So, we would have a way to walk the entire settings, validate against a whitelist of acceptable keys and perhaps values, or value types, as well.  Closest I could find was this comment I made a while ago in a BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1358433#c3 .

**Comment by Fryguy** [comment]
If you are just checking for the presence of a key, then perhaps `Settings.marshal_dump.include?(:authentication)`

The method marshal_dump is an OpenStruct method that just returns a Hash of the keys, which you can then use as a lookup table.
