### ISSUE TITLE
Expose api setting  `max_results_per_page` to the api

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-api#136]
As a follow on to #113 UIs would benefit from being able to communicate when there is a hard stop on pagination of results, will prevent showing the user things they can't do

> oh hum I am user, i want to see the next 1000000 instances of this thing, **whaaaa** why do i only see 10 !!!! ITS A BUG ITS A BUG ITS A BUG

<3

**Comment by abellotti** [comment]
In api.yml, we can just add api as an exposed category in settings.

```
   :settings:
     ...
     :categories:
+    - api
       - product
       - prototype
```

so GET /api/settings

```
{
  "api": {
    "token_ttl": "10.minutes",
    "authentication_timeout": "30.seconds",
    "max_results_per_page": 1000
  },
  "product": {
    "maindb": "ExtManagementSystem",
    "container_deployment_wizard": false,
    "datawarehouse_manager": false
  },
  "prototype": {
    "queue_type": "miq_queue",
    "artemis": {
      "queue_hostname": "localhost",
      "queue_port": 61616,
      "queue_username": "admin"
    },
    "amazon": {
      "s3": false
    },
    "ems_vmware": {
      "update_driven_refresh": false
    }
  }
}
```
 
GET /api/settings/api/max_results_per_page should also work just like GET /api/settings/product/maindb does but it does not.  Probably a bug,  /cc @imtayadeway can you take a 👀  ?

**Comment by chrisarcand** [comment]
@AllenBW The settings call solution that seems to be accepted here is fine; to be fair on knowing the limit *in the paginated calls* is usually not a thing, and just knowing your max results is usually the norm. See the Google Analytics or GitHub V3 API as examples.

**Comment by AllenBW** [comment]
Hi @chrisarcand 👋 

Yep! I'm down with what was proposed above, unsure what examples you are referring to. Just looking to avoid the situation of user surprise, where the resulting behavior does not match the expected behavior.

**Comment by imtayadeway** [comment]
Closing as this seems to be resolved....feel free to continue discussion/reopen as necessary.
