### ISSUE TITLE
bulk query don't work if model guid is implemented as a virtual attribute.

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-api#192]
problem exposes itself when trying to add support for bulk post "query" for /api/container_images
- see guid is an alias method to docker_id.

**Comment by JPrause** [comment]
@abellotti is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
