### ISSUE TITLE
[RFE] GraphQL

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-api#198]
Adding a graphQL interface for the API would be awesome (this would be an addition to, not a replacement)

**Comment by chriskacerguis** [comment]
@miq-bot all_label enhancement

**Comment by chriskacerguis** [comment]
@miq-bot add_label enhancement

**Comment by imtayadeway** [comment]
I'm moving this issue to a Pivotal story and cross-linking....please feel free to continue discussion/track there

**Comment by imtayadeway** [comment]
See https://www.pivotaltracker.com/story/show/153220319
