### ISSUE TITLE
href slug refactoring

### ISSUE THREAD

**Issue by jntullo** [ManageIQ/manageiq-api#208]
Spent some (probably too much) time attempting to refactor href slugs, but thought it was time for an issue around it...

Currently, the way of grabbing a resource's `href_slug` is via the [virtual attribute](https://github.com/ManageIQ/manageiq/blob/5059d08ba18312f600dfa5c4734168ab3c346467/lib/extensions/ar_href_slug.rb) which is essentially calling [name for subclass](https://github.com/ManageIQ/manageiq-api/blob/8f30e9cd9894e302add1729d7aa7bb54764db33b/lib/api/collection_config.rb#L77-L82). Name for subclass is problematic here, because it is only looking to see whether the resource class is equal to that of a collection class or a descendant of one - and doesn't do any more searching once it finds one that matches that criteria. 

There are multiple scenarios (ie `requests`, `policy_actions`, `vms`) where the href slug is incorrect because the resource class is a descendant of a class specified by a different collection than the request that was made to access the resource. Which brings me to the question - what is the purpose of an href slug?

If the purpose is to be a shortened version of an `href`, then why do we go through all of this trouble with a virtual attribute that looks through the config? We can base it directly off of the request and build it similarly to the href.

If the purpose is to find the specific href, or collection that matches the resource's class *exactly* (ie when an Automation Request is returned from `/requests`, it should return an href slug with `/automation_requests/:id`), then it still needs to be refactored to look for exact matches and not break when it finds a descendant.

FWIW, QE thinks it should be [consistent with the href](https://bugzilla.redhat.com/show_bug.cgi?id=1503852#c4)

cc: @chrisarcand @imtayadeway @abellotti

**Comment by abellotti** [comment]
I agree the ones provided by the API should be consistent with the accessed collection.

When handing off objects to Ansible playbooks, we provide them href_slugs for accessing our objects via the API.  The model fetches the href_slug directly by calling the href_slug helper method in lib/extensions/ar_href_slug.rb so it's not always fetching them via API requests.  Grep for href_slug in the main repo.

**Comment by abellotti** [comment]
I wonder if in general we should overload build_href_slug for all collections in API, we're always starting the the type (collection) anyways and not the klass.

**Comment by jntullo** [comment]
@abellotti that's what I was leaning towards after your first comment - it seems that the current virtual attribute works for what's needed when handing off objects to Ansible playbooks, but doesn't fit the purpose (just using the type) for the API.

**Comment by chrisarcand** [comment]
Thanks for opening this @jntullo as you've basically outlined where I'm totally confused as to what's considered an `href_slug`. I think the linked BZ represents my thought best: 

> I would expect the "href_slug" to respect the "href".

The bottom line is that in the API people expect a [URL slug](https://en.wikipedia.org/wiki/Semantic_URL#Slug) but it looks like it was written with class hierarchy in mind, which doesn't make sense (now, at least - maybe it once did in the past).  This can be as simple as a single method in the base controller that takes routing in to account.

The Ansible playbook bit is different animal and should be named as such, as a different attribute if needed.

**Comment by jntullo** [comment]
Closed via https://github.com/ManageIQ/manageiq-api
