### ISSUE TITLE
Calling service_orders/cart/service_requests endpoint returns a 404 if no cart exists

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-api#22]
Calling the service_orders/cart/service_requests endpoint returns a 404 when a cart does not exist; and then the client can create one.  I'm wondering everyone's thoughts on changing the behavior such that if you call the endpoint when a cart does not exist, if it can just go ahead a create one and return nothing.

It pertains to this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1480758

Thoughts?

Chris

**Comment by imtayadeway** [comment]
Closing this as stale but feel free to reopen if there is still interest
