### ISSUE TITLE
[RFE] Downloading the Reports via API.

### ISSUE THREAD

**Issue by cNeha** [ManageIQ/manageiq-api#234]
Looking for the API request for downloading the reports or exporting the reports

**Comment by imtayadeway** [comment]
I created a pivotal story for this RFE here: https://www.pivotaltracker.com/story/show/153412719. I'll close this issue but feel free to continue discussion.

**Comment by imtayadeway** [comment]
On second thoughts, reopening for visibility

**Comment by JPrause** [comment]
@cNeha is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
