### ISSUE TITLE
[BUG] Adding attribute 'description' limits fields returned to only those in attributes but doesn't include 'description'

### ISSUE THREAD

**Issue by nmaludy** [ManageIQ/manageiq-api#241]
# Steps to reproduce

### Send HTTP command (Postman)

```shell
GET https://server.domain.tld/api/vms?expand=resources&attributes=operating_system.product_name,description
```

### Response

```json
{
    "name": "vms",
    "count": 2,
    "subcount": 2,
    "resources": [
        {
            "href": "https://server.domain.tld/api/vms/100000000000208",
            "id": 100000000000208,
            "operating_system": {
                "product_name": "Red Hat Enterprise Linux Server release 7.4 (Maipo)"
            }
        },
        {
            "href": "https://server.domain.tld/api/vms/100000000000154",
            "id": 100000000000154,
            "operating_system": {
                "product_name": "SUSE Linux Enterprise Server 11 (x86_64)\nVERSION = 11\nPATCHLEVEL = 3"
            }
        },
    ]
}
```

As you can see no "description" is returned in the objects"

If you remove the `description` field the full VM object is returned with the additional attributes specified in the query.

### Edit

Appears that if i add any attribute present on the "base" object then it outputs just the fields specified in `attributes` (example: `vendor`, `guid`, etc). This is exactly what i'm after in #242 . Is this desired behavior, and can i count on it in a future release?

Still, `description` is not returned when limited in this way.

**Comment by abellotti** [comment]
That is the correct behavior, if you ask for specific attributes you’d just get those. It could be that description is nil thus not returned. If you get the VM with no attributes specified is description returned ?

**Comment by nmaludy** [comment]
@abellotti ah yes, you're right description is NULL in the database.

I would expect that this would be returned and just set to `null` in the JSON object?

**Comment by abellotti** [comment]
That is not the current behavior, by design. lotsa fields in some of those models. One option is for you to default above attribute access to null if not there.

**Comment by chrisarcand** [comment]
@abellotti Wait what? That seems pretty confusing without any context; what's the reasoning for us wanting to have that designed behavior then?

**Comment by abellotti** [comment]
since early days we don't return nil values, that was for minimizing payloads. The confusion here because the client asked for the particular attribute (via attributes=...) and they don't see it.  From a semantics perspective, bug is that we should return it because they asked for it correct ?

**Comment by chrisarcand** [comment]
Yes; as discussed in Gitter, let's go ahead and remove all this functionality around omitting attributes if nil and relying on nil'ing and removing encrypted attrs.

**Comment by jvlcek** [comment]
I am closing this issue as it was resolved by https://github.com/ManageIQ/manageiq-api/pull/253

**Comment by JPrause** [comment]
@miq-bot close_issue
