### ISSUE TITLE
404's are responded via HTML

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/manageiq-api#265]
If you request any random garbage path, the default "page you were looking for doesn't exist (404)" HTML is rendered back to the client. We should be returning a JSON response.

**Comment by abellotti** [comment]
we had that since v1 of the API, but got lost sometimes in 2.x with the refactoring to leverage rails routing for the collections.

**Comment by imtayadeway** [comment]
@chrisarcand does this happen in production?

**Comment by chrisarcand** [comment]
> with the refactoring to leverage rails routing for the collections.

@abellotti O_o How did routing work in V1?

> does this happen in production?

@imtayadeway I don't know but had that thought as well, most projects I've been on this sort of problem varies between environments, you're right. All envs should be checked; in this case I was just in development (which should still respond appropriately, of course)

**Comment by abellotti** [comment]
v1/early v2, Rails routing basically has 3 entries (one per method) for /api, api base controller did the rest (pun intended 😏  ).

**Comment by imtayadeway** [comment]
@chrisarcand completely agree, I'm just struggling to remember the full reasons why we didn't get this fixed when it first came up. There's some discussion here that may be beneficial to link:

https://github.com/ManageIQ/manageiq/issues/9869

**Comment by chrisarcand** [comment]
> api base controller did the rest

😐 (for @jrafanie)

**Comment by JPrause** [comment]
@abellotti is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by abellotti** [comment]
Returning now the json on bogus url's so we're good.

```
{
  "status": 404,
  "error": "Not Found"
}
```
