### ISSUE TITLE
Remove validation on Authentication class

### ISSUE THREAD

**Issue by imtayadeway** [ManageIQ/manageiq-api#267]
...that it respond to `create_in_provider_queue`. This should always be the case, and if not, needs to be addressed.

Link: https://github.com/ManageIQ/manageiq-api/blob/756d14df2faffc13cbec50c25af74e22d3a8b1be/lib/services/api/authentication_service.rb#L5-L6

**Comment by JPrause** [comment]
@gtanzillo @abellotti is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
