### ISSUE TITLE
Find a better way to test posts with query params

### ISSUE THREAD

**Issue by imtayadeway** [ManageIQ/manageiq-api#269]
There's an open issue for this in rake-test: https://github.com/rack-test/rack-test/issues/150. However, I don't see this moving ahead soon.

Alternatively, it may be better to respond to this test pain by figuring out a better way to implement this.

Links:
https://github.com/ManageIQ/manageiq-api/blob/47010cec9af5b80993df29af93a94cd9775ae1a5/spec/requests/providers_spec.rb#L370-L371
https://github.com/ManageIQ/manageiq-api/blob/47010cec9af5b80993df29af93a94cd9775ae1a5/spec/requests/providers_spec.rb#L1209-L1210

**Comment by JPrause** [comment]
@gtanzillo @abellotti is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
