### ISSUE TITLE
Can't know if password/auth_key changed

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-api#27]
For security reasons, API omits on GET /users password field, /providers endpoints password, auth_key (and maybe userid?) fields etc.  Makes sense.
This caused several problems when developing ansible modules, that try to use API in idempotent style.

1. You can't compare existing to desired to decide if to POST the edit.  The only way to do an idempotent update is always do the POST.  That's actually OK.
2. You can't report `"changed": true / false` correctly, which is considered important in ansible.  Have to always assume `true` :-(

    - Not knowing whether anything changed complicates polling for auth validation (that is only queued on changes).  I'll elaborate in another issue.

=> The solution I propose is API should return a "changed" boolean.  Security wise, the only info it would leak is whether you already knew the credential, which is already something you can test.

cc @yaacov

**Comment by JPrause** [comment]
@cben is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by cben** [comment]
Would still be nice, but in itself it's minor pain point, closing.
#28 is more significant.
