### ISSUE TITLE
Don't bypass authorization by rendering resources on  OPTIONS requests

### ISSUE THREAD

**Issue by imtayadeway** [ManageIQ/manageiq-api#271]
The OPTIONS response for container deployments was rendering back resources in the response - bypassing both authentication and RBAC. The current implementation made a workaround for this - making authentication optional so as to give some protection to this data while preserving the CORS contract. The resources however are still freely given without going through RBAC.

This needs to be refactored out of the OPTIONS request as it does not qualify as metadata, and sets an extremely bad precedent. There is no reason why these resources cannot be queried through the regular GET method.

Link: https://github.com/ManageIQ/manageiq-api/blob/24232ca42982d34bf7126abe3ead59389abe5825/app/controllers/api/container_deployments_controller.rb#L8-L25

**Comment by JPrause** [comment]
@gtanzillo @abellotti is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
