### ISSUE TITLE
Move provider attribute validation to models

### ISSUE THREAD

**Issue by jntullo** [ManageIQ/manageiq-api#277]
A ton of validation is done on attributes for the creation of a provider within the Providers controller. This information is different from provider to provider, and should live within the provider itself so that it is easier to maintain and is more provider-specific. 

For example, creating of an Azure provider would like to specify an `azure_tenant_id`, which is an alias for `uid_ems`. Because validation is done on the [columns](https://github.com/ManageIQ/manageiq-api/blob/master/app/controllers/api/providers_controller.rb#L180), it returns a `BadRequestError`. By moving the allowed attributes to the providers themselves, we can eliminate this problem and the other problems that exist when storing logic for many different models in an API controller. 

Validation: https://github.com/ManageIQ/manageiq-api/blob/master/app/controllers/api/providers_controller.rb#L180

Allowed attributes: 
https://github.com/ManageIQ/manageiq-api/blob/master/app/controllers/api/providers_controller.rb#L3-L10

**Comment by JPrause** [comment]
@gtanzillo @abellotti is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
