### ISSUE TITLE
/providers auth validation in foreground

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-api#28]
When adding/editing a provider, it's useful to know whether ManageIQ successfully connects to it.
In UI, you're forced to click [Validate] before you can even press [Add]/[Save].
In API, the create/edit returns immediately, and iff the `Authentication` changed, it's validated in background.
**=> I propose switching to (or adding option to do) foreground validation, returning result immediately in API response.**

Motivation: It's very hard to know if background happened, and what was the result using API.  We did our best in https://github.com/dkorn/manageiq-ansible-module/blob/master/library/manageiq_provider.py with following pain points:

1. It's slow!  The validation itself is seconds (make a few simple network requests), but through the queue it can take a lot, we had to implement 1min timeout returning "added but not validated" answer...  :snail: 
2. No task_id or anything to poll for is returned.  On edit, the old Authenciation already had a valid/invalid status, so how do you know when you see new status?  The only way we found to detect completion is save `last_valid_on` & `last_invalid_on` timestamps before edit and poll for either to change :construction:
3. It's impossible to distinguish not validated yet vs not trying to validate.  Given multiple endpoints & athentications, we had to compare desired/existing to predict which ones are going to be re-validated and poll only those... :game_die: 
    - Due to #27, we don't always know which ones changed.
    - It's sensitive to how ManageIQ decides what to validate.  E.g. last I checked it's `after_save` hook on Authentication, and if you edit Endpoint port or hostname, it doesn't revalidate.  That's a ManageIQ bug, but now it also manifests as API polling side mis-predicting what to poll for...

For now we're omitting auth validation from the first iteration going into upstream ansible https://github.com/ansible/ansible/pull/28273.  cc yaacov
UPDATE: it landed without validation and will remain that way.  The kludges we attempted in dkorn/manageiq-ansible-module are too brittle, won't re-attempt them unless API is improved.

**Comment by cben** [comment]
Tangentially relevant: https://github.com/ManageIQ/manageiq/issues/13167 (changing only endpoint does not queue revalidating its auth).

**Comment by JPrause** [comment]
@cben is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by cben** [comment]
This remains a big pain point in using the providers API.  
UI mostly uses blocking foreground validation (during provider edit).
Background validation may be OK for some "blind" API flows, but is very awkward in any scenario when you care whether it worked.
@miq-bot remove-label stale

Technical risk: foreground validation from API server may not work in deployments where only some zones have connectivity to the provider.  UI has dealt with same situations, though I'm not sure how exactly.

**Comment by himdel** [comment]
This would be a problem. The API or UI workers should never connect to the provider.

I think the best way of making this work would be for the API to return with a task_id, the UI has a `API.wait_for_task(id) => Promise` mechanism to pick that up.

**Comment by cben** [comment]
> This would be a problem. The API or UI workers should never connect to the provider.

Thanks for the definite statement :+1:

But wait, when I add/edit a provider and click the [Validate] or [Save] button, is that blocking validation, or async?
https://github.com/ManageIQ/manageiq-ui-classic/blob/31cab08643e7/app/controllers/mixins/ems_common/angular.rb#L93-L99
IIUC, some providers support `validate_credentials_task` that launches async MiqTask:
https://github.com/ManageIQ/manageiq/blob/hammer-8/app/models/mixins/authentication_mixin.rb#L16-L41
while other providers only support immediate connection attempt from the UI worker.

### Proposal

OK, so it sounds like the path forward for API too must be async.  
We're back to problems from [issue description](https://github.com/ManageIQ/manageiq-api/issues/28#issue-251486937).
Must return task_id!  Should we return it in a PUT/POST response?  Maybe weird (?) and also hard to implement with validation now triggered by model `after_save` hooks :worried:.  What's worse, hooks on edit don't always fire, and client can't know whether they did (especially for password #27).  Does this mean we can't return task_id?

Instead, how about **adding a separate validate action to API, which does return task_id**.
A client that cares would (1) create/edit a provider (2) call validate action (3) poll the task.  Not fun, but at least reliable...

[I don't have time to implement any of this myself]

**Comment by himdel** [comment]
I can't be as definite about the details, sorry, I mostly just know the high-level thing that appliances are not guaranteed to see each other or the internet, so, anything talking directly is probably breaking in *some* setups.

But yeah, I think any such direct access should be treated as a bug.

There is also at least one ansible related API endpoint which creates such a task, and then directly waits for it. But, I think @Fryguy was definite that that's a bug too - :point_up: [June 19, 2019 2:08 PM](https://gitter.im/ManageIQ/api?at=5d0a41cbee09830dde8bb32d).

---

So, yeah, I agree that this needs to be async.

I think there's one more constraint now - the UI needs to validate any such changes *before* saving the changes.

**Comment by martinpovolny** [comment]
Foreground validation is no to be supported as it it against the logic of the project.

Provider validation is being addressed in a separate issue.

--> closing the issue
