### ISSUE TITLE
[RFE] Add ability to create a Git backed automation domain

### ISSUE THREAD

**Issue by fdupont-redhat** [ManageIQ/manageiq-api#354]
It would be great to be able to create a Git backed automation domain through the API.
An example use case is bootstraping a ManageIQ appliance with domains managed with Git.
This would also be helpful in a CI/CD approach as only the dev environment would have non Git domains.

Associated RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1600961

**Comment by Fryguy** [comment]
I thought we already had this from WAY back with automate import.

**Comment by Fryguy** [comment]
I remember this statement from me: https://github.com/ManageIQ/manageiq/pull/9517#issuecomment-232982860  .  Trying to find the follow-up PRs, but I only see the "refresh git based automate domain".

**Comment by fdupont-redhat** [comment]
I do agree with https://github.com/ManageIQ/manageiq/pull/9517#issuecomment-232982860, in that the Git repository should not be exposed on its own. I would expect an API call similar to:

```json
POST /api/automate_domains
{
  "name": "AwesomeDomain",
  "description": "Bob's awesome domain",
  "source": "git",
  "git_repository": {
    "url": "https://github.com/Bob/AwesomeDomain",
    "branch": "production"
  }
}
```

The Git repository object would be created by the backend because the user creates a Git backed domain. Then, in a CI/CD context, there would be developers' domains, with a merge policy. Then, a tool like Jenkins would call the `refresh_from_source` action on the repo when the content of the repo changes.

**Comment by fdupont-redhat** [comment]
@mkanoor what's your opinion on this one ?

**Comment by fdupont-redhat** [comment]
Who is able to do that ? @abellotti @mkanoor

**Comment by ThomasBuchinger** [comment]
+1 This feature would really simplify life for us. 
Are you planning on supporting the other Import formats (zip, yaml) as well? One thing not mentioned until now, which would be crucial for us is the ability to specify the Tenant. 

One thing you guys might want to keep in mind, when implementing that feature is:
There is a potential for producing conflicts in the `__domain__.yaml` if one tries to implement a feature-branch workflow in combination with Tenants (and possibly running the export-scripts on top of it). 
`igortiunov` in the forum explained the problem [here](http://talk.manageiq.org/t/solved-git-flow-for-automate-code/3362/3).

**Comment by jvlcek** [comment]
This issue should be closed as the requested feature has been implemented. Please see:
https://github.com/ManageIQ/manageiq-api/pull/571

Can someone please close this? I do not have the necessary privileges to close this.
