### ISSUE TITLE
Duplicate user id created when authenticating via ext-auth ldap

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-api#369]
In a configuration with external authentication and SSSD/LDAP:
- logging in to UI via userid in the UI creates one user object
- authenticating an API request as userid@domain creates a second user object.

This is on Fine release and UPN user objects (userid@domain) should be used for all.

**Comment by abellotti** [comment]
/cc @jvlcek  this is the issue reported by @linuxboytoo 

Let's chase this down,  should be all the same as per the /api LocationMatch in manageiq-external-auth.conf w.r.t REMOTE_USER attrs.

**Comment by abellotti** [comment]
@linuxboytoo what is your external directory ?  AD, or one of the OpenLDAP variants ?

**Comment by linuxboytoo** [comment]
Active directory

**Comment by abellotti** [comment]
Thanks, Next question :)  You've configured ext-auth via realm join (http://manageiq.org/docs/reference/latest/auth/active_directory) or regular ldap (http://manageiq.org/docs/reference/latest/auth/ldap) ?

**Comment by linuxboytoo** [comment]
http://manageiq.org/docs/reference/latest/auth/active_directory

**Comment by abellotti** [comment]
@jvlcek can you double check where the unique UPN userid went in ?  @linuxboytoo is running on Fine-3, but I only saw domainname stuff in the appliance console in Fine-4.

**Comment by jvlcek** [comment]
Ah! Good point @abellotti Yesterday I had only checked the top of the fine release.
The userid normalization code doesn't show up until Fine-4!

@linuxboytoo Could you upgrade to Fine-4?

**Comment by linuxboytoo** [comment]
Not right now - we intend to move forward to G release after go live next week.  We are trying to work around this issue on fine-3.   So no love for fine-3? 😁

**Comment by JPrause** [comment]
@abellotti is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by jvlcek** [comment]
This issue was resolved  then the userid normalization code was introduced in Fine-4

I am not able close this. @JPrause Please close.
