### ISSUE TITLE
Associated Services and Providers are not returned from generic object instance endpoint

### ISSUE THREAD

**Issue by ahmbas** [ManageIQ/manageiq-api#378]
the json returned from ```https://{{manageiq_host}}/api/generic_objects/{{id}}``` does not contain any associated services or providers, even though the object has them.
Is there a separate endpoint that could provide the associated services and providers?

EX Post body:

```
{
	"associations": {
		"service": [{
			"href": "https://{{manageiq_host}}/api/services/1"
		}],
		"provider": [{
			"href": "https://{{manageiq_host}}/api/providers/1"
		}]
	},
	"generic_object_definition": {
		"href": "https://{{manageiq_host}}/api/generic_object_definitions/1"
	},
	"name": "my_custom_instance",
	"property_attributes": {
		"engine": "orcale",
		"username": "master",
		"region": "default",
		"type": "db",
		"size": 30
	}
}
```

EX response:

```
{
	"href": "https://{{manageiq_host}}/api/generic_objects/1",
	"id": "1",
	"name": "my_custom_instance",
	"uid": null,
	"generic_object_definition_id": "1",
	"created_at": "2018-05-08T10:30:20Z",
	"updated_at": "2018-05-08T10:30:20Z",
	"property_attributes": {
		"size": 30,
		"type": "db",
		"engine": "orcale",
		"region": "default",
		"username": "master"
	},
	"actions": [{
		"name": "edit",
		"method": "post",
		"href": "https://{{manageiq_host}}/api/generic_objects/1"
	}, {
		"name": "delete",
		"method": "post",
		"href": "https://{{manageiq_host}}/api/generic_objects/1"
	}, {
		"name": "delete",
		"method": "delete",
		"href": "https://{{manageiq_host}}/api/generic_objects/1"
	}]
}
```

**Comment by cben** [comment]
Hmm, sounds like one of those cases the API doesn't include something by default, but can if requested.
Found: #50
Try appending `?associations=vms,services` to the URL?

**Comment by JPrause** [comment]
@ahmbas is this still a valid issue? If yes, let me know and I'll remove the stale label. If not can you close. If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
