### ISSUE TITLE
RUD for MiqTemplate (or just read & update)

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-api#381]
Recently @andyvesel created API endpoints for editing Cloud Templates - [create #337](https://github.com/ManageIQ/manageiq-api/pull/337), [read #130](https://github.com/ManageIQ/manageiq-api/pull/130), [update #341](https://github.com/ManageIQ/manageiq-api/pull/341) and [delete #328](https://github.com/ManageIQ/manageiq-api/pull/328).

However, there is no concept of editing **cloud** templates in the UI, there is just a generic MiqTemplate editor (`VmOrTemplate` really).

For a generic MiqTemplate:
  * the only fields that can be currently edited in the UI are `name` and `description`
  * it can't be created, only updated

So, we need to have API endpoint/endpoints to edit both kinds, with the same interface (for the shared fields at least), as the one introduced in #341.

(Delete would fit logically together, but the UI is currently not using the API for deletion.)

https://bugzilla.redhat.com/show_bug.cgi?id=1487114

EDIT: Related to https://github.com/ManageIQ/manageiq-ui-classic/issues/3944, see discussion there

**Comment by andyvesel** [comment]
@skateman @abellotti I was trying to update a template with PUT/PATCH requests, but it only updates attributes for local MIQ database and doesn't make any calls to Fog, so the image can't be updated on the Openstack side. Do we need it to be implemented this way? 
I'm kind of stuck on this issue. So I'll appreciate any thorough and obvious details about this.

**Comment by skateman** [comment]
IMO we should somehow merge the two functionalities (i.e. the one @andyvesel created and the universal one I was trying to do) and call the openstack-specific stuff when needed.

**Comment by himdel** [comment]
What @skateman said :)

Just, 2 more points:

* please make sure you come up with an interface which can be generalized to any provider, no openstack-specific code in the API
* the UiWorker is not guaranteed to be able to communicate with any external provider, and the same goes for the API => the API call should create a task to talk to the provider

**Comment by martinpovolny** [comment]
Ok, so this is relevant for:

https://github.com/ManageIQ/manageiq-ui-classic/issues/3944

Where we need to be able to create openstack images. Do we need an API action that can upload the image? Or just pass in a URL of it?

**Comment by martinpovolny** [comment]
Anyway it seems that for this to move forward work in needed from the core and provider (openstack) side.

**Comment by himdel** [comment]
> Where we need to be able to create openstack images. Do we need an API action that can upload the image? Or just pass in a URL of it?

This was never specified, and uploading would involve uploading a multi-gig image to the api appliance, potentially moving it to a different worker appliance and only then uploading to the provider. So, a public URL might be enough. (Cc @loicavenel, https://bugzilla.redhat.com/show_bug.cgi?id=1487114)

**Comment by mfeifer** [comment]
cc @agrare

**Comment by himdel** [comment]
The BZ was closed as WONTFIX,
closing this issue to match.
