### ISSUE TITLE
hrefs for service dialogs are incorrectly expanded

### ISSUE THREAD

**Issue by d-m-u** [ManageIQ/manageiq-api#387]
<img width="879" alt="screen shot 2018-05-29 at 6 03 36 pm" src="https://user-images.githubusercontent.com/16326669/40688035-a326796e-636a-11e8-979d-04e86fa36cdf.png">

I don't think that that href is valid. It's for a dialog field, a tag control.

**Comment by Fryguy** [comment]
cc @gtanzillo

**Comment by JPrause** [comment]
@d-m-u is this still a valid issue? If yes, lease remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by JPrause** [comment]
Closing issue. If you feel the issue needs to remain open, please either reopen or let me know and it will be reopened. 
@miq-bot close_issue
