### ISSUE TITLE
"undefined method `service_dialog_ident'

### ISSUE THREAD

**Issue by d-m-u** [ManageIQ/manageiq-api#388]
"undefined method `service_dialog_ident' for #<Api::ServicesController:0x007fd53c1b89d8> Did you mean? service_ident",

You can see this error in the SUI when ordering a service dialog from a custom button.

**Comment by Fryguy** [comment]
cc @gtanzillo

**Comment by abellotti** [comment]
looks like it's defined in the service_dialogs controller, but referenced in the service_dialogs subcollection which is problematic when included from the services or service_templates.

**Comment by JPrause** [comment]
@d-m-u is this still a valid issue? If yes, lease remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.
