### ISSUE TITLE
Add CloudVolumeType to v2v API for OpenStack

### ISSUE THREAD

**Issue by vconzola** [ManageIQ/manageiq-api#456]
When creating a TransformationMapping, the TransformationMappingItems look something like

{ source: '/api/data_stores/<ID>, destination: '/api/data_stores/<ID> }

Assuming mapping creation remains the same in the OSP case, in order for us to be able to map from VMWare Storages to OSP CloudVolumeTypes, they would need to be added to the API, and have the href attribute added to the model

**Comment by bthurber** [comment]
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1620228

**Comment by bdunne** [comment]
If I understand the request, we need to expose CloudVolumeTypes API endpoint.

**Comment by vconzola** [comment]
@bdunne That's correct. We need to display it in the IMS UI as part of infrastructure mapping for OpenStack.

**Comment by mfeifer** [comment]
fixed in https://github.com/ManageIQ/manageiq-api/pull/465
