### ISSUE TITLE
Enable bulk assignment of tags for users

### ISSUE THREAD

**Issue by Hyperkid123** [ManageIQ/manageiq-api#459]
I am now working on tag assignment React component for users in MIQ. You can edit multiple tags for multiple users at once. If i want to use API i have to create one request per user to edit their tags. That is not very pretty sollution.

Is it possible to add bulk assignment of tags to users (like for vms of services)?

**Comment by Hyperkid123** [comment]
@miq-bot assign @skateman

**Comment by skateman** [comment]
@Hyperkid123 here you go :beers:
