### ISSUE TITLE
Query of subcollection resource in a provider is broken

### ISSUE THREAD

**Issue by jameswnl** [ManageIQ/manageiq-api#491]
`providers/1/vms/10`
`providers/2/vms/10`

would give you the same VM which has db record id=10

Similarly with
`providers/1/folders/10`
`providers/2/folders/10`
Same folder object will be returned.

**Comment by juliancheal** [comment]
@jameswnl I'll take a look.

**Comment by djberg96** [comment]
@jameswnl @juliancheal Could this be because the other provider id is really just the network manager or storage manager for that cloud manager?

**Comment by jameswnl** [comment]
As far as I can recall, they are different providers/managers not necessarily related.

**Comment by djberg96** [comment]
I was not able to duplicate what you're describing. I was able to specify a different provider and get the same resources, but that's because the other provider was a network provider with the cloud manager as its parent.

**Comment by jameswnl** [comment]
I am able to pull in the same `vm` from a `Tower` provider and a `rhev` provider

**Comment by jameswnl** [comment]
@djberg96 ok this one should have them all
http://pastebin.test.redhat.com/708055

**Comment by djberg96** [comment]
Interesting. Does it happen for other types of resources? Or just vms?

**Comment by jameswnl** [comment]
I think custom_attributes as well

**Comment by djberg96** [comment]
Yep, seeing the same thing, it's like it's ignoring the provider ID.

**Comment by djberg96** [comment]
Hm, I don't see a subcollection or subresource action defined for vms on providers.

**Comment by martinpovolny** [comment]
Yes. When accessing `providers/1/vms/151` or `providers/3/vms/151` you get the same VM (with `ID=151`) regardless the fact that the VM does/does not belong to the provider (1 or 3).

However with `providers/1/vms` or `providers/3/vms` you get the correct list of VMs (associated with the provider 1 or 3 respectively).

I am not sure this has to be considered a bug. @abellotti : WDYI?

**Comment by abellotti** [comment]
@martinpovolny interesting.  I think semantically it is a bug. i.e. more on a POST than a GET, one is asking to do an action on a vm subresource, but within the context of that provider. But should be consistent for all http verbs. I just don't know what status code is appropriate here, maybe just 404.

**Comment by martinpovolny** [comment]
@abellotti : If you think so, I'd fix the behavior to return a 404 in these cases.

It surely makes more sense to me that way.

**Comment by bdunne** [comment]
Does it make sense to support any actions (get, post, patch, delete) on sub-resources?  If you know the sub-resource id and want to do something with it, you can access it through the primary collection.

**Comment by abellotti** [comment]
We support actions on sub-resources, while a plain REST action can be thought of fine/only working on the primary collection resource, we do expose actions via post and delete for example that rely on the URL structure for the semantic for managing the sub-resource of the owning collection resource. One example like assigning/unassigning/etc. policies, policy_profiles, lans, etc of a primary resource, there may be others.

**Comment by bdunne** [comment]
I don't see how `DELETE api/providers/1/vms/1` would differ from `DELETE api/vms/1`.  Is there a better example that we can discuss?

**Comment by abellotti** [comment]
DELETE /api/providers/:id/custom_attributes/:ca_id
POST /api/vms/:vm_id/policy_profiles/:policy_profile_id    { "action" : "resolve" }
...

they're out there.
