### ISSUE TITLE
Add/Remove CustomButton(s) to CustomButtonSet

### ISSUE THREAD

**Issue by ZitaNemeckova** [ManageIQ/manageiq-api#539]
It's impossible to add/remove a CustomButton to/from CustomButtonSet via API but it's possible to change `set_data[:button_order]` that only says in what order buttons go. It would good to add it as well so UI can only call API and not use extra http request to do it :)

@miq-bot assign @skateman 

Related to https://github.com/ManageIQ/manageiq-ui-classic/pull/4913

**Comment by skateman** [comment]
I see two possible ways how this can be added to the API:
* `custom_buttons` as a subcollection of `custom_button_sets`, IMO this doesn't really make sense because a button can be also unassigned
* passing a `custom_button_set_id` when creating/editing a `custom_button` and doing the necessary db changes in the `Api::CustomButtonsController` under `create_resource` and `edit_resource`

I vote for the 2nd option, but I might need some help with error handling.

**Comment by skateman** [comment]
Another idea thanks to @himdel: having a `before_save` callback on the `CustomButtonSet` models that maps `button_order` to the `members=` method:
```ruby
  before_save :update_members
  def update_members
    self.members = CustomButton.find(set_data[:button_order])
  end
```

I really like this idea, but I don't want to introduce asymmetry with other parts of the API that I don't know :worried: so it would be really nice if I'd have some input on these options from someone who understands the codebase a little better.

**Comment by djberg96** [comment]
I guess I don't see the issue with making `custom_button` a subcollection of `custom_button_sets`. If you need to create an unassigned button, don't use the custom_button_set api.

**Comment by himdel** [comment]
My concern is that we currently have 2 independent places where we list the custom buttons associated with the set (one as an array of ids in `button_order`, and the other as an unordered(? - my assumption) set in `members` (or `children`)).

If we had a nice way of having our subcollection, and custom-ordering it too, without that duplication, it would be perfect :).

**Comment by gtanzillo** [comment]
@abellotti and I looked at this today

We were thinking that you could have an action on `custom_button_sets` that allows for assigning one or more buttons to the set 

```json
        POST /api/custom_button_sets/:id

                actions -> "assign_custom_buttons"
                        
                        "resources" : [
                                { "href" : "/api/custom_buttons/1" },
                                { "id" : "2" },
                                { "href" : "/api/custom_buttons/3" },
                        ]

                actions -> "unassign_custom_buttons"

                        "resources" : [
                                { "href" : "/api/custom_buttons/1" },
                                { "id" : "2" },
                        ]

```
In addition to that we were thinking that it would also be good to allow assigning all the buttons in the set on the `create` and `edit`
```json
POST /api/custom_button_sets                    - create

        {
                data ....,
                "custom_buttons" : [
                        { "href" : "/api/custom_buttons/1" },
                        { "id" : "2" },
                        { "href" : "/api/custom_buttons/3" }
                ]
        }


POST /api/custom_button_sets                    - edit


        {
                "action" : "edit",
                "resource" : {
                        "custom_buttons" : [
                                { "href" : "/api/custom_buttons/1" },
                                { "id" : "2" },
                                { "href" : "/api/custom_buttons/3" }
                        ]
                }
        }
```

**Comment by skateman** [comment]
@gtanzillo the important part not to miss is the button order, just saying so we won't forget about it.
