### ISSUE TITLE
Very first request sometimes causes Circular dependency error on ConversionHost

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#544]
@Hyperkid123 told me about his problem that sometimes his very first API request fails with a HTTP 500 and there's no deterministic way to reproduce it. When I was playing with the API, I also experienced this issue in production and found out that there's a [traceback](https://pastebin.com/cZ9Nxa1D) in the api.log. Then I looked into my local api.log and found out that I had those tracebacks all the time :cry: :sweat_smile: :pray: 

So as far I could understand, this has to do something with [this fix](https://github.com/ManageIQ/manageiq-api/pull/416) created by @jrafanie. I tried looking at the affected `ConversionHost` from any possible angle, but I don't know how this could be a circular dependency. My theory is that there are two models trying to load `ApplicationRecord` at the same time.

@miq-bot add_label bug

**Comment by skateman** [comment]
Hm, after thinking this through, there are actually 2 requests fired from the UI almost simultaneously, so this might explain my theory with the threads.

**Comment by jrafanie** [comment]
yeah, 2 threads are trying to autoload at the same time.  This sounds very much like the issue we "worked around" using the permit concurrent loads.  Is this with the fix in #416?

**Comment by skateman** [comment]
@jrafanie yes, this is happening with the latest master and the latest upstream build as well.

**Comment by himdel** [comment]
Also seeing this.. https://gist.github.com/himdel/36eb11d45a33f076c91047098648ddbf

Happened to me during testing https://github.com/ManageIQ/manageiq-ui-classic/pull/5164,

URL http://localhost:3000/api/notifications?expand=resources&attributes=details&sort_by=id&sort_order=desc&limit=100

Status 500 Internal Server Error

Content-Type application/json; charset=utf-8

Data {"error":{"kind":"internal_server_error","message":"Circular dependency detected while autoloading constant ContainerProject","klass":"RuntimeError"}}

**Comment by jrafanie** [comment]
I couldn't recreate it this @skateman @himdel @Hyperkid123.  Can you try running with the rack lock debugging middleware for a few days:

Add rails lock debugging middleware to config/application.rb:
`config.middleware.insert_before Rack::Sendfile, ActionDispatch::DebugLocks`

If it gets the 500 error, please provide the following information:
`curl -L http://admin:smartvm@localhost:4000/rails/locks` or whatever port your web service /api worker is listening on.

looking at both of your gists, it looks like there are two requests locking each other, an /api/auth and /api/notifications, so I tried this on my machine and appliance:


```ruby
2.times do
  Thread.new do
    `curl -k -L http://admin:smartvm@localhost:3000/api/auth?requester_type=ws`
  end

  Thread.new do
    `curl -k -L http://admin:smartvm@localhost:3000/api/notifications?expand=resources&attributes=details&sort_by=id&sort_order=desc&limit=100`
  end

end
```

**Comment by skateman** [comment]
@jrafanie this might be a heisenbug :confused: I was able to reproduce this only once by accident since I inserted the middleware. However, the `/rails/locks` was is getting back with an empty response.

**Comment by himdel** [comment]
Can confirm that after the request returns a 500, `/rails/locks` is empty.

But that makes sense really. If there is a locking problem, it gets resolved when that exception throws, right?

Managed to catch the locks a bit before, but not sure if this is already processing both api requests...

https://gist.github.com/himdel/f515442221c387746ffbe3adbcd65ee0

**Comment by himdel** [comment]
But I can't reproduce the second time .. maybe something to do with the files being cached?

Changing `activesupport-5.0.7.1/lib/active_support/dependencies.rb:510`:

```diff
         expanded.sub!(/\.rb\z/, ''.freeze)
 
         if loading.include?(expanded)
+          `curl -L http://admin:smartvm@localhost:3000/rails/locks > /tmp/locks.$$`
           raise "Circular dependency detected while autoloading constant #{qualified_name}"
         else
           require_or_load(expanded, qualified_name)
```

And hoping this will happen again.

**Comment by himdel** [comment]
This is what my /api/notifications endpoint returns: https://gist.github.com/himdel/b762953ab803d9c60e3ea81b76974b71

**Comment by himdel** [comment]
Got a fresh one: `Circular dependency detected while autoloading constant MiqAlertStatus`

locks: https://gist.github.com/himdel/f839ec7ae39198a69185c0f5c28b7267

**Comment by jrafanie** [comment]
@himdel @Hyperkid123 @skateman I opened PR #550 with the first thing I got to work.  Details are there.
