### ISSUE TITLE
Endpoint to validate (Cloud)Provider credentials

### ISSUE THREAD

**Issue by Hyperkid123** [ManageIQ/manageiq-api#585]
I need an endpoint that will validate credentials for provider `connection_configurations`  (endpoints, amqp, rsa).

Currently is done in ui-classic. For cloud managers its `/ems_cloud`. There is also some strange attributes mapping. The `type` attribute is mapped to `emstype` for some reason and so on. I would like to keep the API attribute names.

**Comment by Hyperkid123** [comment]
@miq-bot assign @skateman

**Comment by skateman** [comment]
My quick idea is to add a `POST /api/providers/validate` endpoint that would handle any supported provider. What do you think @gtanzillo @abellotti ?

**Comment by skateman** [comment]
@miq-bot rm_label stale
@miq-bot add_label pinned

**Comment by gtanzillo** [comment]
This should be supported now that DDF forms have been implemented across all providers.
