### ISSUE TITLE
[V2V] Private key information should be filtered out in log

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-api#595]
When submitting private key information the private key information is being logged into the evm.log or api.log (or both). This needs to be filtered out.

At the moment this is not easy to remove because the filters are largely a series of hard coded keys set in `Vmdb::Settings::PASSWORD_FIELDS`. I think we would have to temporarily redefine `Api.encrypted_attribute` to make it work.

**Comment by Fryguy** [comment]
Ideally this should be made pluggable so a plugin can bring its own set of filtered keys.

**Comment by djberg96** [comment]
Moved over here: https://github.com/ManageIQ/manageiq-v2v/pull/996
