### ISSUE TITLE
Saving dialog not using transaction

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-api#630]
When saving a dialog via the API, it looks like all the tabs (and fields, groups) get created *before* the dialog.

That's fine, but the operation is not wrapped in a transaction, so when dialog validation fails, those extra tabs stay created.

Worse, if those tabs have any `dialog_id` (when copying from a different dialog), that `dialog_id` will not get replaced by the new dialog id on validation error, so failing to create a dialog via the API can actually affect tabs of existing dialogs.

(This is related to https://bugzilla.redhat.com/show_bug.cgi?id=1713100,
but since https://github.com/ManageIQ/manageiq-ui-classic/pull/5856 the UI is no longer sending those obsolete ids,
so this affecting other dialogs can not be reproduced from the UI, only via the API,
but you can still see extra unassociated dialog tabs after trying to create a dialog with a duplicate name (`DialogTab.where(:dialog_id => nil).count` should never be nonzero).)

**Comment by himdel** [comment]
@miq-bot remove_label stale
@miq-bot add_label pinned

Still an issue.

**Comment by d-m-u** [comment]
Closed in 20013, @himdel, let me know if there's anything I missed, please.

**Comment by himdel** [comment]
Thanks, tested by trying to copy a dialog with the same name, without https://github.com/ManageIQ/manageiq-ui-classic/pull/5856/commits/4962568f5586895f95fc7d0b7093737e4d3de041 .

Validation fails successfully, and there seem to be no artifacts remaining afterwards :)
