### ISSUE TITLE
[RFE] Add tag assignment for cloud volumes

### ISSUE THREAD

**Issue by lodgenbd** [ManageIQ/manageiq-api#638]
Currently it appears the tags method is not available for cloud_volumes. I see that other cloud resources were eventually added for tagging such as networks that were not previously available, so I wanted to request that this one be added. This is especially important given my other issue (https://github.com/ManageIQ/manageiq-providers-openstack/issues/495) I created discussing when creating a cloud instance (openstack) with a tag, the associated resources aren't also automatically tagged which is the expectation from a normal everyday end user. I am seeking functionality to tag cloud_volumes via API as not only a workaround for my above issue, but also for general everyday automation I would like to use it with.

**Comment by Fryguy** [comment]
cc @agrare

**Comment by martinpovolny** [comment]
closed via https://github.com/ManageIQ/manageiq-api/pull/685
