### ISSUE TITLE
[RFE] Rename service attribute display to visible

### ISSUE THREAD

**Issue by lfu** [ManageIQ/manageiq-api#672]
Service attribute `display` is renamed to `visible` in ManageIQ/manageiq-schema#410.

An alias has been added so `service.display` still works. After all occurance of `service.display` have been replaced by `service.visible` in UI and API, the alias would be removed in a new release.

**Comment by martinpovolny** [comment]
@lfu : what is leading you to the conclusion that a change is needed on the API side?

```
lucifer ruby-2.5.5 - [~/Projects/manageiq-api] (master)$ grep -r display app/ lib/
app/controllers/api/api_controller.rb:          :display_name => engine.plugin_name,
lucifer ruby-2.5.5 - [~/Projects/manageiq-api] (master)$ 
```

Thx!

**Comment by lfu** [comment]
That is good if there is no change to be done on API side for the `service.visible` rename. Just to make sure API is aware and ready for the change.
Thanks for looking into this!
