### ISSUE TITLE
Manifest upload endpoint for V2V

### ISSUE THREAD

**Issue by martinpovolny** [ManageIQ/manageiq-api#715]
Details in https://github.com/RedHatCloudForms/cfme-migration_analytics/issues/27

**Comment by agrare** [comment]
@martinpovolny I expected this to live in the cfme-migration_analytics API

**Comment by martinpovolny** [comment]
> @martinpovolny I expected this to live in the cfme-migration_analytics API

I missed that completely in the previous discussion. Ok
