### ISSUE TITLE
Automation request with FQNAME

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#722]
I'm working on the new React/DDF dialog editor and player and trying to load some dynamic dialog fields through the API. I found the [docs](https://www.manageiq.org/docs/reference/latest/api/examples/automation_request) about how initiate an automation request, however, I can't really work further with the current request body format.

```json
{
  "version" : "1.1",
  "uri_parts" : {
    "namespace" : "System",
    "class" : "Request",
    "instance" : "InspectME",
    "message" : "create"
  },
  "parameters" : {
    "var1" : "xxxxx",
    "var2" : "yyyyy",
    "var3" : 1024,
    "var4" : true,
    "var5" : "last value"
  },
  "requester" : {
    "user_name" : "admin",
    "auto_approve" : true
  }
}
```

For the `uri_parts` object I'd have to implement a parsing of automate URIs on the client side, which AFAIK can't be done without polling the API to determine which part of the URI is what kind. Ideally, I'd need a `uri` or `fqname` (pick one) parameter that can substitute the `uri_parts` object.

I also have my concerns about the `requester` part, why would I have to send the `user_name` if the API requires authentication?

@martinpovolny @tinaafitz

**Comment by skateman** [comment]
I was able to backtrace this issue to the `MiqRequestWorkflow.parse_ws_string` method, that accepts this `uri_parts`. Is there any way to build the result of this method from the fqname instead of the `uri_parts`?

**Comment by martinpovolny** [comment]
@tinaafitz : could someone from automate help with this a bit?

**Comment by gmcculloug** [comment]
@skateman I assume you are asking for the player part as the editor some not be running the automate resolution.  @eclarizio Can you help identify the API calls that they want to make here, I know the current player does not use `automation_requests` to run the dynamic method for dialogs.

**Comment by skateman** [comment]
@gmcculloug yes, we can't preseed the dynamic fields with the data from automate as we do it during serialization in the current implementation, so I need a solution to pull in the initial dynamic values.

**Comment by eclarizio** [comment]
@skateman I *think* what you're looking for is here, maybe: https://github.com/ManageIQ/manageiq-api/blob/master/app/controllers/api/service_dialogs_controller.rb#L22. If you can't use this API directly, then this is probably at least the general idea of what you're looking for as to how we do it right now.

This ends up calling the `#content` method on the dialog model, which creates a new `ResourceActionWorkflow`, and during that, it ends up setting all of the correct values (https://github.com/ManageIQ/manageiq/blob/master/app/models/resource_action_workflow.rb#L133).

Does that help at all?

**Comment by skateman** [comment]
I guess so, I can figure it out. We had a discussion with @tinaafitz and @Fryguy last week and they both agreed that the current API-way of running automate jobs is painful, so I guess the issue will stay valid, but not really blocking me anymore.

@miq-bot assign @tinaafitz 
@miq-bot rm_label question

**Comment by skateman** [comment]
After digging deep in this world, my conclusion is that I still need this more fqname-friendly endpoint. All the current `ResourceAction` based implementation becomes useless in the moment when we "flatten" the dialog structure. Therefore, depending on the old structure would just introduce more tech debt :confused:

**Comment by gtanzillo** [comment]
Ping @Fryguy
