### ISSUE TITLE
GET api?attributes=authorization should return more than an array of strings for `groups`

### ISSUE THREAD

**Issue by AllenBW** [ManageIQ/manageiq-api#74]
While mildly helpful, the array of strings, better would be an array of full group objects that below to the user when this call is made:`GET http://localhost:3000/api?attributes=authorization`

```
  "identity": {
    "userid": "admin",
    "name": "Administrator",
    "user_href": "http://localhost:3000/api/users/10000000000001",
    "group": "EvmGroup-super_administrator",
    "group_href": "http://localhost:3000/api/groups/10000000000002",
    "role": "EvmRole-super_administrator",
    "role_href": "http://localhost:3000/api/roles/10000000000001",
    "tenant": "Red Hat",
    "groups": [
      "Tenant My Company access",
      "EvmGroup-super_administrator"
    ]
  }
```

@imtayadeway 👾 💅 ‼️

**Comment by abellotti** [comment]
keeping current groups array returned as is (ye-old compatibility) but maybe some additional details separately.  

@AllenBW what info out of groups do you need ?  with all groups details, might be tons of data, we may want to only return that if attributes=authorization, "identity" is always returned but we can extend with an miq_groups element when attributes=authorization

**Comment by AllenBW** [comment]
see i did that! added the `miq_groups` attribute... it didn't do much... all i need/want is an id or href for the groups, of course can be gotten by doing a call on `api/groups` and matching in the client... but that kinda seems crazy to make another call :-/

**Comment by abellotti** [comment]
If this is something you need back with each call with attributes=authorization,

Maybe something like this ?

```
  "identity": {
    "userid": "admin",
    "name": "Administrator",
    "user_href": "http://localhost:3000/api/users/10000000000001",
    "group": "EvmGroup-super_administrator",
    "group_href": "http://localhost:3000/api/groups/10000000000002",
    "role": "EvmRole-super_administrator",
    "role_href": "http://localhost:3000/api/roles/10000000000001",
    "tenant": "Red Hat",
    "groups": [
      "Tenant My Company access",
      "EvmGroup-super_administrator"
    ],
    "miq_groups" : [
        {
           "description" : "Tenant My Company access",
           "href" : "http://localhost:3000/api/groups/1000000000021",
           "id" : "1000000000021"
        },
        {
            "description" : "EvmGroup-super_administrator",
            "href" : "http://localhost:3000/api/groups/1000000000002",
             "id": "1000000000002",
        }
    ]
  }
```

**Comment by AllenBW** [comment]
@abellotti GOSH YES!!!! This would save the day
