### ISSUE TITLE
/api/vms/{id}/policies does not return the policies in the policy profiles assigned to the VM

### ISSUE THREAD

**Issue by gtanzillo** [ManageIQ/manageiq-api#745]
To reproduce:

1. Create a policy and add it to a profile
2. Assign the policy to a VM
3. Request to VM policies from the API -

http://localhost:3000/api/vms/10000000000112/policies

The result has no policy references -

```json
{
    "name": "policies",
    "count": 16,
    "subcount": 0,
    "pages": 1,
    "resources": [],
    "actions": [
        {
            "name": "assign",
            "method": "post",
            "href": "http://localhost:3000/api/vms/10000000000112/policies"
        },
        {
            "name": "unassign",
            "method": "post",
            "href": "http://localhost:3000/api/vms/10000000000112/policies"
        },
        {
            "name": "resolve",
            "method": "post",
            "href": "http://localhost:3000/api/vms/10000000000112/policies"
        }
    ],
    "links": {
        "self": "http://localhost:3000/api/vms/10000000000112/policies?offset=0",
        "first": "http://localhost:3000/api/vms/10000000000112/policies?offset=0",
        "last": "http://localhost:3000/api/vms/10000000000112/policies?offset=0"
    }
}
```

**Comment by d-m-u** [comment]
@miq-bot assign @d-m-u

**Comment by d-m-u** [comment]
Ugh, fine. AB's right as usual. The UI add is a policy_profile add, and 

http://localhost:3000/api/vms/#/policy_profiles shows the correct profiles. I don't have the power to close issues so maybe GT wants to verify this and then he can close it?

**Comment by chessbyte** [comment]
@gtanzillo ^

**Comment by gtanzillo** [comment]
I discussed this with Alberto and this would be the correct way to get the actual policies assigned to a resource -

http://localhost:3000/api/vms/10000000000229/policy_profiles?expand=resources&attributes=miq_policies

Unfortunately, this does not currently work either and needs to be fixed

**Comment by chessbyte** [comment]
Part of https://github.com/ManageIQ/manageiq-api/issues/782
