### ISSUE TITLE
API policy assignment assigns policies when it should assign only policy profiles 

### ISSUE THREAD

**Issue by gtanzillo** [ManageIQ/manageiq-api#755]
For example the request

`POST /api/vms/320/policies`
```json
{
  "action" : "assign",
  "resource" : { "href" : "http://localhost:3000/api/policies/7" }
}
```
```json
{
  "results": [
    {
      "success": true,
      "message": "Assigning Policy: id:'7' description:'test_control_policy' guid:'b1fd23bc-acc4-11e4-abc7-b8e85646e742'",
      "href": "http://localhost:3000/api/vms/320",
      "policy_id": "7",
      "policy_href": "http://localhost:3000/api/policies/7"
    }
  ]
}
```
Assigns an `MiqPolicy` object to the specified VM.  But the UI only allows a user to assign a policy profile (`MiqPolicySet`) to a resource.

Furthermore, the API does not support assigning a policy profile to a resource.

**Comment by chessbyte** [comment]
Maybe this is not necessarily a bad thing in the API

**Comment by abellotti** [comment]
Lookin' at the api.yml, policy_profiles are subcollections to clusters, hosts, providers, vms, templates, resource_pools, with the declared actions "assign" and "unassign", so those would be done via POST /api/vms/:id/policy_profiles.  {action: "assign"} for example.

**Comment by abellotti** [comment]
I think this is fine, we expose both as documented here: https://www.manageiq.org/docs/reference/latest/api/reference/policies

**Comment by gtanzillo** [comment]
Cool, thanks @abellotti @chessbyte!
