### ISSUE TITLE
Weird behavior on /api/providers when asking for more than 3 attributes

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#776]
When I ask for up to 3 attributes, I get all the extra data like this:
```js
// GET /api/providers/22?attributes=authentications,endpoints,zone_name
{
  "href": "http://localhost:3000/api/providers/22",
  "id": "22",
  "name": "RHV",
  "created_on": "2017-10-25T16:20:08Z",
  "updated_on": "2019-04-07T00:01:21Z",
  "guid": "9e293565-9e9f-4475-a82e-fab7d52577ba",
  "zone_id": "9",
  "type": "ManageIQ::Providers::Redhat::InfraManager",
  "api_version": "4.2.8.2-0.1.el7ev",
  "uid_ems": null,
  "host_default_vnc_port_start": null,
  "host_default_vnc_port_end": null,
  "provider_region": null,
  "last_refresh_error": null,
  "last_refresh_date": "2019-04-07T00:01:21Z",
  "provider_id": null,
  "realm": null,
  "tenant_id": "1",
  "project": null,
  "parent_ems_id": null,
  "subscription": null,
  "last_metrics_error": null,
  "last_metrics_update_date": null,
  "last_metrics_success_date": null,
  "tenant_mapping_enabled": null,
  "enabled": true,
  "options": {},
  "zone_before_pause_id": null,
  "last_inventory_date": null,
  "authentications": [
...
```
But when I add a 4th attribute, only the specified attributes show up:
```js
// GET /api/providers/22?attributes=authentications,endpoints,zone_name,provider_id
{
  "href": "http://localhost:3000/api/providers/22",
  "provider_id": null,
  "id": "22",
  "authentications": [
...
```

I think this is pretty inconsistent and it should behave the same way for any number of attributes. This is blocking https://github.com/ManageIQ/manageiq/issues/18818

@miq-bot add_label bug

**Comment by skateman** [comment]
Okay, found a workaround, but the issue is still super confusing ...

**Comment by abellotti** [comment]
This is the behavior of the api in general, i.e. not provider specific.  By default, you get all direct attributes, unless you ask for specific direct attributes (associations aside), then you only get them.  In the above example, asking for provider_id triggered that behavior.

In your example, asking for specific direct attributes (provider_id), plus associations, that's what the API returned. If you ask for specific associations and no direct attributes, then you get all direct attributes plus the associations asked for.

Hope this clarifies things a bit.

**Comment by bdunne** [comment]
@skateman Does https://github.com/ManageIQ/manageiq-api/issues/776#issuecomment-599663953 resolve this issue?

**Comment by skateman** [comment]
Yeah
