### ISSUE TITLE
Enhancement to support check_compliance action

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-api#790]
Adding support for **check_compliance** action which parallels the Classic-UI's "Check Compliance of Last Known Configuration" under Policy,

i.e.
```
  Compute->Infrastructure->Providers->Policy->Check Compliance of Last Known Configuration
  Compute->Infrastructure->Hosts->Policy->Check Compliance of Last Known Configuration
  Compute->Infrastructure->Virtual Machines->Policy->Check Compliance of Last Known Configuration
  ... 
```

API action _check_compliance_ to be implemented for the the following API endpoints and the related product identifiers for the role entitlement:

| API Endpoint                     |  Product Identifier(s) |
| -------------                     | -------------------- |
| /api/cloud_templates       | image_check_compliance |
| /api/container_groups      | container_group_check_compliance |
| /api/container_images      | container_image_check_compliance |
| /api/container_nodes        | container_node_check_compliance |
| /api/hosts                            | host_check_compliance |
| /api/instances                     | instance_check_compliance |
| /api/providers                     | ems_infra_check_compliance, ems_cloud_check_compliance |
| /api/templates                    | miq_template_check_compliance |
| /api/vms                              | vm_check_compliance |

**Classic-UI Feedback**:

Sample Response for single VM:
- Check Compliance initiated for 1 VM and Instance from the ManageIQ Database

Sample Responses when Targeting Multiple VMs:
- No Compliance Policies assigned to one or more of the selected items
- Check Compliance initiated for 2 VMs and Instance from the ManageIQ Database

**API Usage**:

_Resource requests:_

Request:
```
POST /api/vms/171
```

```
{
  "action" : "check_compliance"
}
```

Response:
```
{
  "success" : true,
  "message": "VM id:171 name:'aab-ldap' check compliance requested",
  "task_id": "35",
  "task_href": "http://localhost:3000/api/tasks/35",
  "href": "http://localhost:3000/api/vms/171"
}
```

Request:
```
POST /api/vms/173
```

```
{
  "action" : "check_compliance"
}
```

Response:
```
{
  "success" : false,
  "message": "VM id:173 name:'aab-idp' has no compliance policies assigned",
  "href": "http://localhost:3000/api/vms/173"
}
```

_Collection bulk requests:_

Request:
```
POST /api/vms
```

```
{
  "action" : "check_compliance",
  "resources" : [
     { "id" : "171" },
     { "id" : "173" },
     { "id" : "175" }
  ]
}
```

Response:
```
{
  "results": [
    {
      "success": true,
      "message": "VM id:171 name:'aab-ldap' check compliance requested",
      "task_id": "36",
      "task_href": "http://localhost:3000/api/tasks/36",
      "href": "http://localhost:3000/api/vms/171"
    },
    {
      "success": false,
      "message": "VM id:173 name:'aab-idp' has no compliance policies assigned",
      "href": "http://localhost:3000/api/vms/173"
    },
    {
      "success": true,
      "message": "VM id:175 name:'aab-keycloak' check compliance requested",
      "task_id": "37",
      "task_href": "http://localhost:3000/api/tasks/37",
      "href": "http://localhost:3000/api/vms/175"
    }
 ]
}
```

**Comment by abellotti** [comment]
Implementation of check_compliance for the API endpoints
 [ ] /api/vms - https://github.com/ManageIQ/manageiq-api/pull/795

**Comment by gtanzillo** [comment]
@lfu Please see Alberto's list above for the additional classes that need to have the compliance check action exposed. You can follow the pattern Alberto established in /api/vms

**Comment by chessbyte** [comment]
@gtanzillo @abellotti if this is now complete with all the PRs by @lfu that were recently merged, please close this issue.

**Comment by abellotti** [comment]
afaik this can now be closed.  @gtanzillo ?

**Comment by gtanzillo** [comment]
Closing, thanks @abellotti, @lfu!
