### ISSUE TITLE
ManageIQ API: /api/reports/:id/results/:id does not return unit in result_set

### ISSUE THREAD

**Issue by morningspace** [ManageIQ/manageiq-api#798]
Steps to reproduce:

* Create chargeback, rate, and report on ManageIQ UI
* Queue a report to generate the result for that report
* Retrieve the report result by calling REST API, e.g.
```
curl -k -g -X GET -H "Accept: application/json" -H "X-Auth-Token: ${AUTH_TOKEN}" "${BASE_URL}/api/reports/1000000000147/results/1000000000172"
```

Expected results:

As UI developer, I can find the unit along with the value returned in the result_set field, so that I know how to render report on UI.

Actual results:

The result_set field in the JSON payload does not include the unit.

Here's an example:
```
{
  "href": "https://cloudforms50bod.rtp.raleigh.ibm.com/api/reports/1000000000147/results/1000000000172",
  "id": "1000000000172",
  "name": "Chargeback for VM alloc - Accounting",
  "miq_report_id": "1000000000147",
  "miq_task_id": "1000000005603",
  "userid": "brian_so",
  "report_source": "Requested by user",
  "db": "ChargebackVm",
  "report": {
    "id": null,
    "name": "Chargeback for VM alloc - Accounting",
    "title": "Chargeback for VM alloc - Accounting",
    "rpt_group": "Custom",
    "rpt_type": "Custom",
    "priority": null,
    "db": "ChargebackVm",
    "cols": [
      "start_date",
      "display_range",
      "vm_name",
      "cpu_cost",
      "chargeback_rates",
      "memory_allocated_cost",
      "memory_allocated_rate",
      "memory_allocated_metric",
      "memory_cost",
      "storage_allocated_metric",
      "storage_cost",
      "cpu_allocated_cost",
      "cpu_allocated_rate",
      "total_cost"
    ],
    "include": {
      "managed": {
        "columns": [
          "department"
        ]
      }
    },
    "col_order": [
      "vm_name",
      "display_range",
      "managed.department",
      "cpu_cost",
      "chargeback_rates",
      "memory_allocated_cost",
      "memory_allocated_rate",
      "memory_allocated_metric",
      "memory_cost",
      "storage_allocated_metric",
      "storage_cost",
      "cpu_allocated_cost",
      "cpu_allocated_rate",
      "total_cost"
    ],
    "headers": [
      "VM Name",
      "Date Range",
      "My Company Tag Department",
      "CPU Total Cost",
      "Chargeback Rates",
      "Memory Allocated Cost",
      "Memory Allocated Rate",
      "Memory Allocated over Time Period",
      "Memory Total Cost",
      "Storage Allocated",
      "Storage Total Cost",
      "vCPUs Allocated Cost",
      "vCPUs Allocated Rate",
      "Total Cost"
    ],
    "conditions": null,
    "order": "Ascending",
    "sortby": [
      "vm_name",
      "start_date"
    ],
    "group": "y",
    "graph": null,
    "dims": null,
    "created_on": null,
    "updated_on": null,
    "filename": null,
    "file_mtime": null,
    "categories": [],
    "timeline": null,
    "template_type": "report",
    "where_clause": null,
    ... ...
  },
  "created_on": "2020-03-17T20:49:38Z",
  "scheduled_on": null,
  "last_run_on": "2020-03-17T20:49:43Z",
  "last_accessed_on": "2020-03-23T13:30:23Z",
  "report_rows_per_detail_row": null,
  "miq_group_id": "1000000000022",
  "result_set": [
    {
      "start_date": "2020-03-17T00:00:00.000Z",
      "display_range": "03/17/2020",
      "vm_name": "ansible-tower",
      "cpu_cost": null,
      "chargeback_rates": "Default",
      "memory_allocated_cost": null,
      "memory_allocated_rate": null,
      "memory_allocated_metric": null,
      "memory_cost": null,
      "storage_allocated_metric": "8589934592.0",
      "storage_cost": "20.0",
      "cpu_allocated_cost": null,
      "cpu_allocated_rate": null,
      "total_cost": "20.0",
      "managed.department": "Accounting",
      "id": null
    },
    {
      "start_date": "2020-03-17T00:00:00.000Z",
      "display_range": "03/17/2020",
      "vm_name": "apparent-mastodon-master-1",
      "cpu_cost": null,
      "chargeback_rates": "Default",
      "memory_allocated_cost": null,
      "memory_allocated_rate": null,
      "memory_allocated_metric": null,
      "memory_cost": null,
      "storage_allocated_metric": "268435456000.0",
      "storage_cost": "20.0",
      "cpu_allocated_cost": null,
      "cpu_allocated_rate": null,
      "total_cost": "20.0",
      "managed.department": "Accounting",
      "id": null
    }
  ]
}
```

There are two records in the result_set field as above. Take the first record as example, 
* "storage_allocated_metric": "8589934592.0",
* "storage_cost": "20.0",

From ManageIQ UI, I can see the report result display the two values as below:
* Storage Allocated: 8 GB
* Storage Total Cost: $20.00

This seems to be handled at server-side then returned back to client via API calls that are dedicated to ManageIQ UI as below:
```
/report/tree_select?id=xx-1000000000147_rr-1000000000172
```

Though the returned response is a JSON payload, it actually wraps the whole bunch of HTML piece including the transformed value with unit that is used by ManageIQ UI directly.

**Comment by lpichler** [comment]
@morningspace

API supports formatted output in `result_set` - it was added [here](https://github.com/ManageIQ/manageiq-api/pull/547) when we added filtering for `result_set`.

you need to add  `?hash_attribute=result_set` to get formatted results.

(Currently, it is needed to specify `sort_by` column for chargeback report results also)

then request can look

```
/api/results/24216?hash_attribute=result_set&sort_by=vm_name
```

Response:

```
"scheduled_on": null,
    "last_run_on": "2019-04-07T00:00:19Z",
    "last_accessed_on": "2019-04-07T00:00:19Z",
    "report_rows_per_detail_row": null,
    "miq_group_id": "1",
    "result_set": [
        {
            "vm_name": "localhost",
            "display_range": "Nov 2018",
            "cpu_allocated_cost": "",
            "cpu_used_metric": "",
            "cpu_used_cost": "",
            "memory_allocated_cost": "",
            "memory_used_metric": "",
            "memory_used_cost": "",
            "disk_io_used_metric": "",
            "disk_io_used_cost": "",
            "net_io_used_metric": "",
            "net_io_used_cost": "",
            "storage_allocated_metric": "16 GB",
            "storage_allocated_cost": "$494.00",
            "storage_used_metric": "7.38 GB",
            "storage_used_cost": "$7,296.00"
        }
    ],
    "count": 1,
    "subcount": 1,
    "pages": 1
}
```


@morningspace please let me know whether this solves your issue.

thanks

**Comment by morningspace** [comment]
@lpichler Thanks for looking into it.

I tried your suggested approach on my local env, it looks it does not work. The API call that I made is as below:

```
$ curl -k -X GET -H "Accept: application/json" -H "X-Auth-Token:$AUTH_TOKEN" "$MIQ_URL/api/reports/1000000000147/results/1000000000172?hash_attribute=result_set&sort_by=vm_name"
```

Is it because the deployment that I'm using is a bit old although I noticed the PR has been merged almost one year ago.

By digging into it further, it looks at least the PR was included in [ivanchuk-1-beta1](https://github.com/ManageIQ/manageiq-api/releases/tag/ivanchuk-1-beta1), where I can see the API version is [4.1.0](https://github.com/ManageIQ/manageiq-api/commit/2fa11aeafb342d1765b191d13af72c7c9b756a2a).

And, when I check my env:
```
$ curl -k -X GET -H "Accept: application/json" -H "X-Auth-Token:$AUTH_TOKEN" "$MIQ_URL/api"
{
  "name": "API",
  "description": "REST API",
  "version": "4.1.0",
  "versions": [
    {
      "name": "4.1.0",
      "href": "https://my_cloudform_server/api/v4.1.0"
    }
  ],
  ...
```

Anything I missed?

**Comment by lpichler** [comment]
@morningspace 

thanks for the description and yes that's right and feature is already in `ivanchuk-1-beta1`,

hovewer feature is available on collection `api/results`

`/api/results/24216?hash_attribute=result_set&sort_by=vm_name`

and there is used subcollection `results` in your example.

Is it OK for you to use
`/api/results/XXX?hash_attribute=result_set&sort_by=vm_name`  instead of 
`/api/report/results/XXX?hash_attribute=result_set&sort_by=vm_name`  ?

**Comment by morningspace** [comment]
@lpichler Just to confirm the `result_id` here is exactly the same id that I was using in form of `reports/{report_id}/results/{result_id}`, right?

I tried that just now and it works well. I'm going to bring this to the team and see if that's OK for UI side... then I'll get back to you...

**Comment by lpichler** [comment]
> @lpichler Just to confirm the `result_id` here is exactly the same id that I was using in form of `reports/{report_id}/results/{result_id}`, right?
> 

Correct, it is same id.

**Comment by chessbyte** [comment]
@morningspace closing this issue as resolved.  If it does not work for you, please re-open this issue.
