### ISSUE TITLE
[RFE] API Support for Network/LAN tagging

### ISSUE THREAD

**Issue by ashkuren** [ManageIQ/manageiq-api#801]
Although network tagging is available from within ManageIQ, it's not available via API.
Network collection endpoint: `/api/lans`
Subcollection `/api/:lan_id/tags` not accessible.

It's also missing in the list of collections available for tagging:
https://www.manageiq.org/docs/reference/latest/api/reference/tagging

**Comment by d-m-u** [comment]
@miq-bot assign @d-m-u

**Comment by d-m-u** [comment]
should be closed by 804, @ashkuren, could you please give it a spin and let us know if it suits?

**Comment by ashkuren** [comment]
Hi @d-m-u ,
It works as expected. Thank you! I leave the issue open for docs update?

**Comment by d-m-u** [comment]
Cool, thanks. Yeah, that's fine.
