### ISSUE TITLE
Slow API requests

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-api#805]
This issue will be a toplevel issue with links to subissues as we find which fixes solve each one.

Here is a listing of the most common API requests from a customer log with frequency of each request:

```
11767 Started GET "/api/policy_profiles?expand=resources&expand=resources,policies"
9630 Started GET "/api/availability_zones?expand=resources&attributes=type,id,name"
8200 Started GET "/api/services?expand=resources&filter[]=retired=false&attributes=vms,created_at,name,id"
7439 Started GET "/api/vms?expand=resources&attributes=name,vendor,type,last_compliance_status,tags,power_state,v_owning_datacenter,service,cloud,storage,availability_zone_id&filter[]=active=true"
7427 Started GET "/api/cloud_volumes?expand=resources&attributes=vms,size"
7377 Started GET "/api/providers?expand=resources&attributes=name,type,last_compliance_status,aggregate_vm_cpus,aggregate_vm_memory,vms"
2202 Started GET "/api/vms?expand=resources&filter[]=last_compliance_status=true&filter[]=active=true"
2202 Started GET "/api/vms?expand=resources&filter[]=active=true"
2202 Started GET "/api/vms?expand=resources&attributes=last_compliance_status,tags,v_owning_datacenter&filter[]=active=true"
2202 Started GET "/api/providers?expand=resources&attributes=name,id,vms"
2200 Started GET "/api/policies?expand=resources"
2199 Started GET "/api/vms?expand=resources&filter[]=last_compliance_status=false&filter[]=active=true"
2198 Started GET "/api/policy_profiles/49?expand=resources&expand=policies"
2198 Started GET "/api/policy_profiles/18?expand=resources&expand=policies"
2197 Started GET "/api/policy_profiles/16?expand=resources&expand=policies"
2196 Started GET "/api/policy_profiles/17?expand=resources&expand=policies"
```

**Note, the numbers below were done with the tip of ivanchuk branch since that's the version they were using, we should definitely see if master is better or worse for these.**

Below are the above requests with the median request/completed time on my laptop using a customer db.  Note, the numbers are only important relevant to each other.

- [ ] `Started GET "/api/cloud_volumes?expand=resources&attributes=vms,size"`
  `Completed 200 OK in 4321ms (Views: 0.1ms | ActiveRecord: 968.0ms)`
- [ ] `Started GET "/api/vms?expand=resources&attributes=last_compliance_status,tags,v_owning_datacenter&filter[]=active=true"`
  `Completed 200 OK in 3222ms (Views: 0.1ms | ActiveRecord: 445.1ms)`
- [ ] `Started GET "/api/providers?expand=resources&attributes=name,type,last_compliance_status,aggregate_vm_cpus,aggregate_vm_memory,vms"`
  `Completed 200 OK in 2241ms (Views: 0.1ms | ActiveRecord: 55.3ms)`
- [ ] `Started GET "/api/vms?expand=resources&attributes=name,vendor,type,last_compliance_status,tags,power_state,v_owning_datacenter,service,cloud,storage,availability_zone_id&filter[]=active=true"`
  `Completed 200 OK in 2716ms (Views: 0.1ms | ActiveRecord: 563.3ms)`
- [ ] `Started GET "/api/providers?expand=resources&attributes=name,id,vms"`
  `Completed 200 OK in 1690ms (Views: 0.1ms | ActiveRecord: 23.6ms)`
- [ ] `Started GET "/api/vms?expand=resources&filter[]=active=true"`
  `Completed 200 OK in 1582ms (Views: 0.1ms | ActiveRecord: 15.0ms)`

Below, it looks like there's a penalty of around 200 ms just doing a basic request, perhaps, authentication?

- [ ] `Started GET "/api/policies?expand=resources"`
  `Completed 200 OK in 245ms (Views: 0.1ms | ActiveRecord: 15.8ms)`
- [ ] `Started GET "/api/vms?expand=resources&filter[]=last_compliance_status=true&filter[]=active=true"`
  `Completed 200 OK in 243ms (Views: 0.1ms | ActiveRecord: 14.8ms)`
- [ ] `Started GET "/api/vms?expand=resources&filter[]=last_compliance_status=false&filter[]=active=true"`
  `Completed 200 OK in 234ms (Views: 0.1ms | ActiveRecord: 13.8ms)`
- [ ] `Started GET "/api/services?expand=resources&filter[]=retired=false&attributes=vms,created_at,name,id"`
  `Completed 200 OK in 276ms (Views: 0.1ms | ActiveRecord: 19.3ms)`
- [ ] `Started GET "/api/policy_profiles?expand=resources&expand=resources,policies"`
  `Completed 200 OK in 252ms (Views: 0.1ms | ActiveRecord: 13.8ms)`
- [ ] `Started GET "/api/policy_profiles/49?expand=resources&expand=policies"`
  `Completed 200 OK in 219ms (Views: 0.1ms | ActiveRecord: 6.7ms)`
- [ ] `Started GET "/api/policy_profiles/18?expand=resources&expand=policies"`
  `Completed 200 OK in 227ms (Views: 0.1ms | ActiveRecord: 8.8ms)`
- [ ] `Started GET "/api/policy_profiles/16?expand=resources&expand=policies"`
  `Completed 200 OK in 238ms (Views: 0.1ms | ActiveRecord: 7.2ms)`
- [ ] `Started GET "/api/policy_profiles/17?expand=resources&expand=policies"`
  `Completed 200 OK in 226ms (Views: 0.1ms | ActiveRecord: 7.5ms)`
- [ ] `Started GET "/api/availability_zones?expand=resources&attributes=type,id,name"`
  `Completed 200 OK in 228ms (Views: 0.1ms | ActiveRecord: 6.5ms)`

**Comment by abellotti** [comment]
Very interesting, thanks @jrafanie for getting this information.  I'm curious of the log time span in which the above frequencies have been observed.  Two things that may be of interest:
- Why the high frequencies for queries that essentially get all records, i.e. like refreshing a data set view with all policy profiles, vms, etc. and why aren't those requests with paging enabled.
- From the API logs, it would be useful to also calculate the average time taken per such request: i.e. for a GET /api/vms,

```
[----] I, [2020-04-21T17:39:44.263666 #70955:3feaa22078b8]  INFO -- : MIQ(Api::VmsController.log_request) API Request:    {:requested_at=>"2020-04-21 21:39:44 UTC", :method=>"GET", :url=>"http://localhost:3000/api/vms"}
[----] I, [2020-04-21T17:39:44.471166 #70955:3feaa22078b8]  INFO -- : MIQ(Api::VmsController.log_request) Authentication: {:type=>"basic", :token=>nil, :x_miq_group=>nil, :user=>"admin"}
[----] I, [2020-04-21T17:39:44.473546 #70955:3feaa22078b8]  INFO -- : MIQ(Api::VmsController.log_request) Authorization:  {:user=>"admin", :group=>"EvmGroup-super_administrator", :role=>"EvmRole-super_administrator", :tenant=>"My Company"}
[----] I, [2020-04-21T17:39:44.473828 #70955:3feaa22078b8]  INFO -- : MIQ(Api::VmsController.log_request) Request:        {:method=>:get, :action=>"read", :fullpath=>"/api/vms", :url=>"http://localhost:3000/api/vms", :base=>"http://localhost:3000", :path=>"/api/vms", :prefix=>"/api", :version=>"4.3.0-pre", :api_prefix=>"http://localhost:3000/api", :collection=>"vms", :c_suffix=>nil, :collection_id=>nil, :subcollection=>nil, :subcollection_id=>nil}
[----] I, [2020-04-21T17:39:44.474299 #70955:3feaa22078b8]  INFO -- : MIQ(Api::VmsController.log_request) Parameters:     {"action"=>"index", "controller"=>"api/vms", "format"=>"json", "body"=>{}}
[----] I, [2020-04-21T17:39:44.561077 #70955:3feaa22078b8]  INFO -- : MIQ(Api::VmsController.log_request) Response:       {:completed_at=>"2020-04-21 21:39:44 UTC", :size=>"2.141 KBytes", :time_taken=>"0.298 Seconds", :status=>200}
```

The `time_taken` in the last Response line above, but average them all for same Request url. This way we can prioritize which API call to dive in first.

**Comment by jrafanie** [comment]
@abellotti wow, you're fast.  I updated the description with the median rails log request timing.  I have some caching solutions for these but wanted to document each one so I can see which solution fixes which request.

**Comment by jrafanie** [comment]
And yes, I agree, adding paging controls and such would be a great option to offer them but in general, I hope there's some easy changes we can make in general to speed all requests.

**Comment by abellotti** [comment]
For the authentication, the api log entry time difference between `API Request:` and `Authentication:` would give us the time taken for authentication.

**Comment by NickLaMuro** [comment]
So regarding this request:

```
"/api/providers?expand=resources&attributes=name,type,last_compliance_status,aggregate_vm_cpus,aggregate_vm_memory,vms"
```

Depending on the use case, the user might be able to get away with just doing `total_vms` instead of `vms`, and that would save a lot:

```
/api/providers
|   ms | queries | query (ms) | rows |
| ---: |    ---: |       ---: | ---: |
| 3661 |      87 |       57.6 | 2267 | --
| 2001 |      87 |       64.3 | 2267 |  |
| 2064 |      87 |       67.9 | 2267 |  | - Before
| 2071 |      87 |       64.5 | 2267 |  |
| 2047 |      87 |       69.3 | 2267 | --
|  234 |      87 |       49.3 | 1722 | --
|  244 |      87 |       51.0 | 1722 |  |
|  322 |      87 |       50.7 | 1722 |  | - After
|  248 |      87 |       52.5 | 1722 |  |
|  245 |      87 |       52.5 | 1722 | --
```

Doesn't save on queries, but drops the amount of data required to serialize significantly.  Again, depends on what is needed by the customer, but that might be a quick fix.

**Comment by NickLaMuro** [comment]
Found some minor gains by making this change:

https://github.com/ManageIQ/manageiq-api/pull/810

**Comment by jrafanie** [comment]
@abellotti found that an api token takes around 16ms whereas basic auth was taking around 240ms:

https://www.manageiq.org/docs/reference/latest/api/overview/auth

```
[——] I, [2020-05-21T15:32:02.646879 #83066:3fc760b63b4c]  INFO —— : MIQ(Api::UsersController.log_request) Response:       {:completed_at=>”2020-05-21 19:32:02 UTC”, :size=>”0.785 KBytes”, :time_taken=>”0.016 Seconds”, :status=>200}
```

```
[——] I, [2020-05-21T15:30:36.387411 #83066:3fc760b63cf0]  INFO —— : MIQ(Api::UsersController.log_request) Response:       {:completed_at=>”2020-05-21 19:30:36 UTC”, :size=>”0.785 KBytes”, :time_taken=>”0.244
```

**Comment by jrafanie** [comment]
From the customer logs, it looks like there were ~41k jwt authentication requests in about 12 hours, or 57 requests per minute.  If they changed to token based authentication, this should significantly improve performance.

**Comment by jrafanie** [comment]
Another datapoint:
* I sampled the requests coming into the production log and they're doing around 70-160 `/api`  requests per minute
* A good number of these requests are taking >1 second. (56%)  18000/33000.  Around 8000 are taking 2+ seconds.
* there's only 875 vms in the database

**Comment by Fryguy** [comment]
I've marked https://github.com/ManageIQ/manageiq-api/pull/810 as `jansa/yes?` cause it does have an improvement and it seems safe

**Comment by jrafanie** [comment]
> Started GET "/api/cloud_volumes?expand=resources&attributes=vms,size"
> Completed 200 OK in 4321ms (Views: 0.1ms | ActiveRecord: 968.0ms)

changing this from `vms` to `vms.name` (`/api/cloud_volumes?expand=resources&attributes=vms.name,size`) drops the response size in one environment from 864kb to 132kb and 23 seconds to 4.

**Comment by jrafanie** [comment]
> /api/vms?expand=resources&attributes=last_compliance_status,tags,v_owning_datacenter&filter[]=active=true
>

Adding an attribute from vms causes the response to not provide all attributes and actions of the vms collection.

`/api/vms?expand=resources&attributes=name,last_compliance_status,tags,v_owning_datacenter&filter[]=active=true"`

1578970 to 62131 bytes response (16 to 8 seconds) before and after.

**Comment by jrafanie** [comment]
> * `Started GET "/api/providers?expand=resources&attributes=name,type,last_compliance_status,aggregate_vm_cpus,aggregate_vm_memory,vms"`
>   `Completed 200 OK in 2241ms (Views: 0.1ms | ActiveRecord: 55.3ms)`

vms is the problem here, requesting only what attribute we want, for example, name, fixes this:

`/api/providers?expand=resources&attributes=name,type,last_compliance_status,aggregate_vm_cpus,aggregate_vm_memory,vms.name`

1351549 bytes before, 2568 after.  13 seconds before, 1 after.

**Comment by jrafanie** [comment]
many of these requests are improved based on findings in https://github.com/ManageIQ/manageiq-api/issues/866
