### ISSUE TITLE
Need the ability to add just created vms to a service

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-api#82]
Proposed signature:

```
POST /api/services/:id

{
  "action" : "add_provider_vms",
  "resource" : {
     "provider" : { "href" : "http://localhost:3000/api/providers/:id" },
     "uid_ems" : [ ... ]
  }
}
```

provider reference should support

```
href
id
href_slug
```

Normal action response signature:

```
{
  "success": true,
  "message": "Service id:1000000000127 name:'test-service' add_provider_vms",
  "task_id": "1000000000022",
  "task_href": "http://localhost:3000/api/tasks/1000000000022",
  "href": "http://localhost:3000/api/services/1000000000127"
}
```

**Comment by abellotti** [comment]
ping @gtanzillo upcoming

/cc @imtayadeway or @jntullo 

/cc @gmcculloug

**Comment by Fryguy** [comment]
> Need the ability to add just created vms to a service

What is the use case for this?  I would expect this to be a backend thing, and not something exposed via the API.  That is, "just created VMs" should be a function of refresh bringing the VM record in existence, and then it would automatically link to the service record behind the scenes.

**Comment by gmcculloug** [comment]
The use case is for resources created through Ansible Playbooks since we do not have visibility into what was created.  During service ordering of a playbook this feature will allow the playbook to connect back and identify the provider resources it was responsible for generating.

**Comment by Fryguy** [comment]
Ah I see...so it's not actually creating vms in the database, but hinting that "this vm that was created is actually this service item".

**Comment by jntullo** [comment]
related ManageIQ PR: https://github.com/ManageIQ/manageiq/pull/16082
