### ISSUE TITLE
ManageIQ API: Support report results export functionality from the Rest API

### ISSUE THREAD

**Issue by gtanzillo** [ManageIQ/manageiq-api#827]
In the UI a user can download report results in Text, CSV, or PDF format. The same functionality is required for the API

![image](https://user-images.githubusercontent.com/76593/81015173-3826e600-8e2c-11ea-9d45-58395d995ed6.png)

**Comment by Fryguy** [comment]
@abellotti @gtanzillo Note that PDF is "special" in that in may not be available depending on whether or not the PDF generator is installed.  We will need to probably return a proper 400 error code when PDF is not available.  In the UI they just completely don't show the PDF button in this case, but we don't have that luxury in the API.  You can use [`PdfGenerator.available?`](https://github.com/ManageIQ/manageiq/blob/master/lib/pdf_generator.rb#L14-L16) to determine availability.

**Comment by gtanzillo** [comment]
@Fryguy That's good to know. Out of curiosity, under what circumstances would the PDF generator not be present?

**Comment by Fryguy** [comment]
> @Fryguy That's good to know. Out of curiosity, under what circumstances would the PDF generator not be present?

The PdfGenerator  is pluggable and currently based on whether or not prince is installed, so in downstream/custom builds it may not be present.  If not installed, the `NullPdfGenerator` will be chosen.

**Comment by abellotti** [comment]
Current report run usage and proposed **download** action on the results:

```
POST /api/reports/370
{
  "action" : "run"
}
```

```
{
  "success": true,
  "message": "running report 370",
  "href": "http://localhost:3000/api/reports/370",
  "result_id": "22",
  "result_href": "http://localhost:3000/api/results/22",
  "task_id": "45",
  "task_href": "http://localhost:3000/api/tasks/45"
}
```

Querying all results of a report:

```
GET /api/reports/370/results
{ 
  "name": "results",
  "count": 21,
  "subcount": 3,
  "pages": 1,
  "resources": [
    { 
      "href": "http://localhost:3000/api/reports/370/results/20"
    },
    { 
      "href": "http://localhost:3000/api/reports/370/results/21"
    },
    { 
      "href": "http://localhost:3000/api/reports/370/results/22"
    }
  ],
  "links": {
    "self": "http://localhost:3000/api/reports/370/results?offset=0",
    "first": "http://localhost:3000/api/reports/370/results?offset=0",
    "last": "http://localhost:3000/api/reports/370/results?offset=0"
  }
}
```

Getting the **created_on** attribute on the results:

```

GET /api/reports/370/results?expand=resources&attributes=created_on
{ 
  "name": "results",
  "count": 21,
  "subcount": 3,
  "pages": 1,
  "resources": [
    { 
      "href": "http://localhost:3000/api/reports/370/results/20",
      "created_on": "2020-05-06T15:32:22Z",
      "id": "20"
    },
    { 
      "href": "http://localhost:3000/api/reports/370/results/21",
      "created_on": "2020-05-06T15:32:56Z",
      "id": "21"
    },
    { 
      "href": "http://localhost:3000/api/reports/370/results/22",
      "created_on": "2020-05-06T15:34:49Z",
      "id": "22"
    }
  ],
  "links": {
    "self": "http://localhost:3000/api/reports/370/results?attributes=created_on&expand=resources&offset=0",
    "first": "http://localhost:3000/api/reports/370/results?attributes=created_on&expand=resources&offset=0",
    "last": "http://localhost:3000/api/reports/370/results?attributes=created_on&expand=resources&offset=0"
  }
}
```

Getting a single result, report will be in the **result_set** attribute.

```
GET /api/reports/370/results/22
```

or just:

```
GET /api/results/22
```

Requesting a **txt**, **csv** or **pdf** download of the report result is done via the **download** action:

```
POST /api/results/22
{
  "action" : "download",
  "report_type" : "csv"
}
```

This triggers an async request of the report and returns an action response as follows:

```

{
  "success": true,
  "message": "Requesting a download of a csv report for Result id:22 name:VMware VM Summary",
  "task_id": "46",
  "task_href": "http://localhost:3000/api/tasks/46"
}
```

The task can then simply be queried for a _Finished_ state:

```
GET /api/tasks/46
{ 
  "href": "http://localhost:3000/api/tasks/46",
  "id": "46",
  "name": "Generate Report result [csv]: 'VMware VM Summary'",
  "state": "Finished",
  "status": "Ok",
  "message": "Generate Report result [csv]",
  "userid": "admin",
  "created_on": "2020-05-06T17:15:29Z",
  "updated_on": "2020-05-06T17:15:30Z",
  "pct_complete": null,
  "context_data": null,
  "results": null, 
  "miq_server_id": "3",
  "identifier": null,
  "started_on": "2020-05-06T17:15:30Z",
  "zone": null,
  "actions": [
    { 
      "name": "delete",
      "method": "post",
      "href": "http://localhost:3000/api/tasks/46"
    },
    { 
      "name": "delete",
      "method": "delete",
      "href": "http://localhost:3000/api/tasks/46"
    }
  ]
}
```

And the result can be obtained with the **task_results** attribute of the task as follows:

```
GET /api/tasks/46?attributes=task_results

{
  "href": "http://localhost:3000/api/tasks/46",
  "id": "46",
  "name": "Generate Report result [csv]: 'VMware VM Summary'",
  "state": "Finished",
  "status": "Ok",
  "message": "Generate Report result [csv]",
  "userid": "admin",
  "created_on": "2020-05-06T17:15:29Z",
  "updated_on": "2020-05-06T17:15:30Z",
  "pct_complete": null,
  "context_data": null,
  "results": null,
  "miq_server_id": "3",
  "identifier": null,
  "started_on": "2020-05-06T17:15:30Z",
  "zone": null,
  "task_results": "\"VM Name\",\"Operating System\",\"Provider\",\"Provider ID\",\"Datacenter\",\"Hypervisor\",\"Storage\",\"Memory\",\"CPU Cores\"\nraab_testing,Red Hat Enterprise Linux 7 (64-bit),dev-vc60,2,dev-vc60-DC,ibm-x3550m4-01.cloudforms.lab.eng.rdu2.redhat.com,19327352832,1024,4\aab-test,Red Hat Enterprise Linux 7 (64-bit),dev-vc60,2,dev-vc60-DC,ibm-x3550m4-01.cloudforms.lab.eng.rdu2.redhat.com,17179869184,2048,1\n
  ... "
}
```

**Comment by abellotti** [comment]
Prototyped and tested above with txt and csv,  will now kick the pdf tires, thanks @Fryguy for the   PDF insights.

**Comment by Fryguy** [comment]
I'm not sure I like the POST with `action: download / report_type: csv`.  To me a download is just a GET, so it shouldn't require a POST.  Does it make sense to instead do one of the following?

- `GET /api/results/22.txt` OR `GET /api/results/22.csv`. This follows standard Rails routing with respect to teh `(:format)` directive which is then accessble as `params[:format]` in the controller.
- `GET /api/results/22` with a header of `Accept: text/plain` or `Accept: text/csv` (or perhaps Content-Type or both)

**Comment by abellotti** [comment]
yea, was battling the above, async request made me move over to the POST action and action result which includes the task reference as we're not returning the txt or csv itself.   Was initially thinking of just GET /api/results/22/csv as an subresource, and have that return the action result with task, but then the REST guidelines were haunting me that a GET should just be that a GET and not change anything.

**Comment by abellotti** [comment]
renaming "download" to "request_download" might make it less painful.
