### ISSUE TITLE
API's for visibility and usability of embedded ansible

### ISSUE THREAD

**Issue by shrinaththube** [ManageIQ/manageiq-api#831]
## Required API's for following functionalities
- API to `add/update/delete` credentials (SCM, machines, etc.) in the embedded ansible
UI path: `Automation --> Ansible --> Credentials`

- API to `add/update/delete/refresh` repositories 
UI path:` Automation --> Ansible --> Repositories`

- API to `delete` playbooks
UI path:` Automation --> Ansible --> Playbooks `

## Required API's for embedded ansible visibility
- API to `get` the list of imported ansible playbooks 
- API to `get` the list of credentials
- API to `get` the list of repositories

**Comment by lpichler** [comment]
Those endpoints are available under different names in API.
this docs is about it https://www.manageiq.org/docs/reference/latest/api/reference/configuration_script_sources.

UI:**Repositories** 
API: **configuration_script_sources** :
`GET /api/configuration_script_sources` - there are examples in [docs](https://www.manageiq.org/docs/reference/latest/api/reference/configuration_script_sources.
) for `add/update/delete/refresh`

UI: **Playbooks**
API: **configuration_script_payloads**
`GET /api/configuration_script_payloads ` 
`GET /api/configuration_script_sources/:id/configuration_script_payloads?expand=resources`
It looks like that delete action is not supported at this moment.

UI: **Credentials**
API: **authentifications**
https://www.manageiq.org/docs/reference/latest/api/reference/authentications
`GET /api/configuration_script_payloads/:id/authentications`


@shrinaththube let me know whether you were looking for those endpoints or if you have more questions, thanks!

**Comment by Fryguy** [comment]
Closing due to @lpichler's response.  Please reopen if you have more questions.
