### ISSUE TITLE
Rest api should return VM system UUID also for querying VM records

### ISSUE THREAD

**Issue by dmetzger57** [ManageIQ/manageiq-api#865]
Original BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1858161

Description of problem:

Every VM/bare metal should have a global unique system UUID, and you could get it by one of the below methods on linux system:

# cat /sys/class/dmi/id/product_uuid 
5BC2AA57-5A2F-4EAF-8991-5EF4B2CC9442

Or 

# dmidecode -s system-uuid
5bc2aa57-5a2f-4eaf-8991-5ef4b2cc9442
The system UUID will be very helpful to reconcile records crossing domains, for example: relate an CF-managed VM  to k8s node.

Please consider to expand rest api to get system UUID also when querying VM records.

**Comment by gtanzillo** [comment]
The system UUID is returned in `uid_ems` for VMware, which should be available via API. Would need to be verified for other providers

**Comment by gtanzillo** [comment]
As stated above, we are able to collect `uid_ems` from VMware providers. That value may or may not be available for other provider types or may require running smart state analysis. But, in all cases, the value is available via the API.

Closing this issue, please reopen if needed.
