### ISSUE TITLE
Add support for querying attributes without expand=resources

### ISSUE THREAD

**Issue by jrafanie** [ManageIQ/manageiq-api#868]
A request such as: `/api/vms?&attributes=name` will silently ignore the requested `name` attribute, returning just hrefs and a 200 response code:

```
    "resources": [
        {
            "href": "http://localhost:3000/api/vms/1"
        },
```

We should honor any requested attributes (real or virtual) and continue to include the `href` when `expand` is not included in the requested URL.

From discussion here: https://github.com/ManageIQ/manageiq-api/issues/866
Also related to slow api requests: https://github.com/ManageIQ/manageiq-api/issues/805

This feature will allow us to make much more performant API requests without breaking compatibility and only minimal changes to clients: (drop `expand=resources`) (a 2 MB response that includes all attributes due to `expand=resources` can become 70 KB without `expand=resources` + only needed attributes)

**Comment by Fryguy** [comment]
There is also a reverse subtlety here where if you pass `/api/vms?expand=resources&attributes=num_cpu` you get back all of the fields plus num_cpu, however if you pass `/api/vms?expand=resources&attributes=name,num_cpu` you only get name and num_cpu, which doesn't seem to make sense (as it's a physical column).  So changing this opens up fixing this oddity.
