### ISSUE TITLE
Accessing zones' NTP servers through the API

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#892]
Most of the form fields are doable either directly or through nested attributes, which is fine. However the NTP servers are accessed in the ui using the `ConfigurationManagementMixin#settings_for_resource`. I am not aware if these per-resource settings are available through the API or not, but I guess it would be easier to just expose the NTP servers somehow through a virtual attribute.

Required for https://github.com/ManageIQ/manageiq-ui-classic/issues/6917

cc @kbrock because my description above mentions `virtual attributes`
FYI @gtanzillo

**Comment by skateman** [comment]
@miq-bot assign @gtanzillo

**Comment by kbrock** [comment]
@skateman Do we need to expose ntp server for every zone? or just the ones that override the settings.

Getting the ntp server runs 5 queries per zone (aka N+1 style)
it even reloads the zone - which I'm working on removing.

Wondering why we even have ntp in our app settings. but that is not a productive question

**Comment by kbrock** [comment]
I'm starting to question why we need an operating system configuration in our app at all.

Setting the ntp server seems very os centric and would be better configured with the other operating system specific parameters in a tool like `cockpit`

**Comment by chessbyte** [comment]
A long, long time ago, NTP setup was critical as workers and appliances heartbeated by updating a time stamp in SQL.  So, if the time stamp was too far off, a false positive timeout would get detected and things would restart.  To the user, it looked like our system was thrashing and restarting itself for no reason.

Maybe it is time to revisit these ancient assumptions

**Comment by kbrock** [comment]
@chessbyte a proper date time is still very much necessary.
But it is not our responsibility to set this operating system parameter.

In the container case, we are not able to change this.
In the appliance case, we will rely upon vmware or `cockpit` to configure this system like it sets the dns server.

**Comment by skateman** [comment]
@kbrock our job with converting to the Zone add/edit form to React would be way easier without the NTP servers, so I'm more than okay with getting rid of them. I understand that in certain situations we might need to set the NTP servers somehow, but I don't even understand why is this setting on the zone level and not on each server separately. 

Oh wait, it's also configurable on a per-server level and it even says that it is able to override per-zone settings:
![Screenshot from 2020-09-24 07-08-55](https://user-images.githubusercontent.com/649130/94103388-de53a680-fe34-11ea-9162-b7f14ddd946a.png)

**Comment by gtanzillo** [comment]
We definitely need to keep the NTP settings for the appliance. But I'm wondering how often users actually need to make changes to the default

**Comment by chessbyte** [comment]
@Fryguy I am thinking that NTP settings should *only* be exposed in the Appliance Console, as they only apply to each appliance and removed from the UI and API.  Thoughts?

**Comment by kbrock** [comment]
@chessbyte can we go one step further and suggest they configure ntp server at the same time and in the same tool that they configure the dns server?

**Comment by chessbyte** [comment]
@kbrock where do they configure DNS server?  Is it not appliance-console?

**Comment by skateman** [comment]
Is it okay if we "forget" to add these fields into the react-converted version of the form? :wink:

**Comment by kbrock** [comment]
@chessbyte ok. I was wrong. dns and static ip is in there. We took out the timezone configuration.
Interestingly in that PR, @jrafanie suggested we would probably want to remove ntp server from the settings and ui as well.

https://github.com/ManageIQ/manageiq-appliance_console/pull/99#pullrequestreview-300309077

Also feels like the tool provisioning this vm would be responsible for setting the ip address

**Comment by kbrock** [comment]
Cockpit allows us to configure the ntp server. interestingly documentation for doing that is on the same page as setting the timezone and date/time

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/chap-configuring_the_date_and_time

I don't know where to look for the ui

**Comment by jrafanie** [comment]
We recently had an issue where a vCenter with terribly out of sync time and caused issues with provisioning because of this.  We made a [change here](https://github.com/ManageIQ/manageiq-providers-vmware/pull/622) 20 days ago to give us more visibility to it when verifying the credentials... So, it's still an issue in 2020.   

With that said, I don't know if users use zone and/or server based ntp settings or something else like cockpit or other tools to keep their appliances, pods, etc. in sync.  It does feel like something we should let other applications handle.  In terms of pods, it sounds like pods should only care about setting timezone as they share the host clock, so you can't actually change the clock in the pods.  It's the responsibility for the host machine to be running ntpd/ntpdate or something similar to keep the host OS's time correct. See this [discussion here](https://stackoverflow.com/a/22820278).

**Comment by chessbyte** [comment]
I think that setting up NTP is very important for appliances, but does not belong in our application.  I can envision the setup in Appliance Console or in some standard environment (Cockpit?) where NTP can be set up for our appliance.

**Comment by Fryguy** [comment]
💯% agree, I've never understood the ntp settings in the application proper

**Comment by bdunne** [comment]
@skateman Should this be closed now that https://github.com/ManageIQ/manageiq/pull/20623 and https://github.com/ManageIQ/manageiq-ui-classic/pull/7369 are merged?
