### ISSUE TITLE
Endpoint for Schedules

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#893]
I found an endpoint for report schedules only, but under Configuration there's also a schedules page that I don't know how to access. I am suspecting that this endpoint could be also utilized when accessing the database backup schedule somehow.

@miq-bot assign @gtanzillo

**Comment by lpichler** [comment]
@miq-bot assign @lpichler

**Comment by lpichler** [comment]
duplicate of https://github.com/ManageIQ/manageiq-ui-classic/issues/7328
