### ISSUE TITLE
Trying to access the tenants' name attribute under service dialogs

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#899]
I'm trying to seed the Service Catalog selection dropdown using the API:
![Screenshot from 2020-09-25 15-24-05](https://user-images.githubusercontent.com/649130/94272412-51e3d980-ff43-11ea-8495-41a3ff041ad5.png)

The catalogs are prefixed with the tenant name and I was wondering if it's possible to request them directly using a single API request. So far the following isn't really working:
```
/api/service_catalogs&expand=resources,tenant
```

@miq-bot add_label question
Related issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/6944

**Comment by skateman** [comment]
@miq-bot assign @gtanzillo

**Comment by abellotti** [comment]
```
GET /api/service_catalogs?expand=resources&attributes=tenant 
```
should do the trick.

**Comment by skateman** [comment]
@gtanzillo I wish all my API issues would have such a simple fix :+1: thanks
