### ISSUE TITLE
Endpoint for ISO datastores

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#909]
There is no endpoint for listing and deleting the `IsoDatastore` entities. No other operations are currently exposed in the UI.

@miq-bot add_label help wanted
@miq-bot assign @gtanzillo

**Comment by lfu** [comment]
There are `create` operations in [IsoDatastore](https://github.com/ManageIQ/manageiq-ui-classic/blob/67c7829f755ac0032ed3187b4b3c88803abd7dcf/app/controllers/pxe_controller/iso_datastores.rb#L6). Is it still valid? @skateman

**Comment by skateman** [comment]
Well, I don't see them in the api.yml :confused:

**Comment by skateman** [comment]
Oh, sorry, you're right, now I get it. Yes please!
