### ISSUE TITLE
[RFE] Expose custom branding data in the API (not filesystem)

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-api#91]
Service UI should be able to support Branding customisation like in Ops UI.

There are 3 Configuration options available in “Custom Logos” in Configuration

- Custom Logo
- Custom login & 'About' Screen background image
- Custom Login Panel Text

From: https://www.pivotaltracker.com/story/show/149340169 
and 
https://docs.google.com/document/d/14SSfpUQtZ52mEv4mW1wPO-KYi52_qWtHGSk83EuhKsA/edit

**Comment by chriskacerguis** [comment]
Also need to add a way to add custom links for the help menu.

**Comment by Fryguy** [comment]
If this gets implemented we may want to discuss the "right" way to do it.  I believe right now there are multiple ways to do branding via MiqServer-level settings as well as tenant level settings.  In the rearch, we are going to possibly need a [new way to do it](https://github.com/ManageIQ/manageiq-design/issues/32#service-providers), so whatever is done should be future-proof.

**Comment by imtayadeway** [comment]
Closing this as stale but feel free to reopen if there is still interest
