### ISSUE TITLE
Endpoint for ISO images

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#910]
There's no endpoint for listing/editing `IsoImage` entities. There are no other operations exposed in the UI.

@miq-bot add_label help wanted
@miq-bot assign @gtanzillo

**Comment by lfu** [comment]
@skateman I don't find there is any reference of `listing` product feature for `IsoImage`. There is only `edit` feature.

**Comment by skateman** [comment]
Yeah, listing is probably not necessary, only retrieving one and editing it.
