### ISSUE TITLE
Endpoint for Host Aggregates

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#911]
There's no endpoint for adding/editing host aggregates and adding/removing hosts from them.

@miq-bot add_label help wanted
@miq-bot assign @gtanzillo

**Comment by skateman** [comment]
@miq-bot assign @skateman 
@miq-bot rm_label help wanted

**Comment by Fryguy** [comment]
Is this done with the merging on #964?  I know it says "Partially", but wasn't sure why.

**Comment by skateman** [comment]
Nope, the add/remove hosts actions still need to be implemented, but that's a different form.

**Comment by skateman** [comment]
There are two additional forms for adding/removing hosts to/from host aggregates:
![Screenshot from 2021-01-13 14-36-26](https://user-images.githubusercontent.com/649130/104459245-c69f5a00-55ac-11eb-8444-0e52b67ca219.png)
![Screenshot from 2021-01-13 14-37-21](https://user-images.githubusercontent.com/649130/104459308-dd45b100-55ac-11eb-9cb8-1171dc1fa360.png)
![Screenshot from 2021-01-13 14-37-10](https://user-images.githubusercontent.com/649130/104459312-ddde4780-55ac-11eb-853b-9eaa59a5ebf4.png)

Would it be reasonable to move these forms into the parent host aggregate form and do the add/remove using the create/edit host aggregate endpoint, or should I keep it as it is and create the two additional API endpoints?

@Fryguy @gtanzillo @NickLaMuro

**Comment by Fryguy** [comment]
I like that idea...what new endpoints would be required?

**Comment by skateman** [comment]
We'd need `add_host` and `remove_host` but only if we don't go with the new approach. If we do, we just need @NickLaMuro's https://github.com/ManageIQ/manageiq-api/pull/916
