### ISSUE TITLE
OPTIONS endpoint that tells us what providers support creating AuthKeyPair

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#915]
We have this piece of code implemented in `ui-classic`:
```ruby
  def ems_form_choices
    assert_privileges("auth_key_pair_cloud_new")
    ems_choices = ManageIQ::Providers::CloudManager.select do |ems|
      ems.class::AuthKeyPair.is_available?(:create_key_pair, ems)
    end
    ems_choices.each do |ems|
      {:name => ems.name, :id => ems.id}
    end
    render :json => {:ems_choices => ems_choices}
  end
```
It's being used in the `AuthKeyPair` create form and I am wondering if there's any API endpoint that would provide us the same? If not, then I think it should be created...

@miq-bot assign @gtanzillo 
FYI @kavyanekkalapu

**Comment by Fryguy** [comment]
@agrare I thought we had this already via support feature mixin?

**Comment by agrare** [comment]
@Fryguy we don't have a supports_feature for create_key_pair, we could add one to the EMS or use `supports_create?` on the `ems.class::AuthKeyPair` model

**Comment by skateman** [comment]
So here I have access to the EMS subclass, but not to the AuthKeyPair one :confused: so it needs to come from the EMS somehow.
