### ISSUE TITLE
Raising an exception in a POST request returns with a 200 response

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#919]
The following request:

```
curl -XPOST -d '{"name": "e", "type": "ManageIQ::Providers::EmbeddedAnsible::AutomationManager::VaultCredential", "vault_password": "x"}' "http://admin:smartvm@localhost:3000/api/authentications" | jq
```

Returns a `200` response:

```
{
  "results": [
    {
      "success": false,
      "message": "must supply a manager resource"
    }
  ]
}
```

Is this correct? Because the UI codebase expects HTTP errors if the request failed :confused:  

@miq-bot add_label bug

**Comment by skateman** [comment]
cc @himdel, we might want to handle this on the `API` object level, like rejecting the promise in a wrapper...

**Comment by skateman** [comment]
@miq-bot add_label question

**Comment by himdel** [comment]
`results: []` ... that's the bug I think .. the API seems to treat this as a bulk request but it isn't

The code for bulk requests has to return 200 + array of successes/failures,
but individual endpoints must return non-200 responses for failures. (The old 4** if the user did something wrongg, 5** if the server did.)

**Comment by himdel** [comment]
>  on the API object level

I don't think we can. Once you have an array of results instead of a single result, we can't just reject.

So I don't think we could do such a workaround for all API request. We can  certainly copypaste it for each of them, but..

**Comment by skateman** [comment]
@miq-bot assign @gtanzillo

This is also a big one, there are already a bunch of affected forms using the UI...

**Comment by Fryguy** [comment]
@abellotti can you take a look?

> the API seems to treat this as a bulk request but it isn't

Yeah, I agree when you are posting a single create, it feels like that should return an error code, but if you post a bulk-create, then it should return an array of success and errors and I'm not sure what code _that_ should be (though 200 feels weird)

**Comment by kbrock** [comment]
ok, current status:

returning `:ok`(i.e.: 200) for creates with success and failure
returning `:not_acceptable` (i.e.: 406) for single creates that fail - this is changing from the previous `:ok` response code.


While we are here, I did look into changing successful creates to `:created` (i.e.: 201) - no other actions has this concept. This is a lot of controller and changes. I don't think the amount of work warrants this change, but am more than happy to make the changes if you all want it

**Comment by skateman** [comment]
@kbrock AFAIK if you just raise an exception without any handling in a request, it returns with a HTTP 500. Why not use that?

**Comment by kbrock** [comment]
sigh. ok current status:

if it is an action request, associated with bulk requests, then it will always return a 200, even if a single entry is added.
If it is not an action request, then the appropriate response code is used.

So the request is driving this instead of the response.

This is a little strange as sometimes action requests are the only way to handle requests, even for a single resource.
But basing the response handling on the request seems like it makes more sense rather than the number of entries in a request driving the way that bulk and action requests behave.

**Comment by skateman** [comment]
@kbrock how is this going?
