### ISSUE TITLE
[RFE] Provider and OS images API

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-api#92]
x-post from: https://github.com/ManageIQ/manageiq-ui-service/issues/1038

It would be super great if the api could serve provider and OS images (by images, I mean the .svg that are generated and stored in public/assets/svg).

- will ensure consistency of icons across UIs
- will reduce bundle size of sui assets
- will be super cool

This discussion is kinda related but also kinda different: https://gitter.im/ManageIQ/manageiq/ui?at=59ce771f7b7d98d30d510fe2

**Comment by imtayadeway** [comment]
Closing this as stale but feel free to reopen if there is still interest
