### ISSUE TITLE
[RFE] Editing values under /api/settings with arbitrary resource paths

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#920]
The verb for this endpoint is just `g`, so there's no way to change the values. This basically blocks the conversion of most of the forms under OPS.

EDIT: editing works, the issue has been changed to an RFE to support requests like:
```
PATCH /api/zones/:id/settings/authentication/amazon_key
```

@miq-bot assign @gtanzillo

**Comment by Fryguy** [comment]
@skateman The /api/settings you cannot change because we don't know what object to apply the change to.  That is, what you are seeing in /api/settings are the rolled up changes from the miq_server, zone, and region.  If you want to change anything then you have to hit /api/miq_servers/:id/settings or /api/zones/:id/settings or /api/regions/:id/settings

**Comment by Fryguy** [comment]
cc @abellotti

**Comment by Fryguy** [comment]
I guess we _could_ make /api/settings basically be "region level", but for now, we already allow region level settings through /api/regions/:id/settings.

**Comment by skateman** [comment]
I need this for the `region`, `zone` and `server` levels as the forms under ops are working with these. The best would be to allow POST to `arbitrary_resource_path`s, i.e. URLs like `/api/zones/:id/settings/authentication/amazon_key` to edit just the specific field.

**Comment by Fryguy** [comment]
I agree...that was the original design we had discussed, if I recall.  @abellotti might know better.

**Comment by abellotti** [comment]
https://www.manageiq.org/docs/reference/latest/api/reference/settings.html

**Comment by NickLaMuro** [comment]
https://github.com/ManageIQ/manageiq-api/pull/275

**Comment by NickLaMuro** [comment]
@skateman @gtanzillo So as @abellotti has mentioned, the settings do exist as part of a subcollection, and are tested here:

https://github.com/ManageIQ/manageiq-api/blob/c02451e9/spec/requests/servers_spec.rb#L198-L207

I also confirmed it works outside of a test context as well against a generic `bin/rails s`:

```ruby
require "json"
require "net/http"

@api_route  = URI("http://localhost:3000/api/servers/1/settings")
@auth_token = nil

def api_request http, type: "get", path: @api_route.path, login: false, payload: nil
  uri     = URI("http://localhost:3000#{login ? "/api/auth" : path}")
  puts uri

  headers = {}
  headers["Accept"]        = "application/json"
  headers["authorization"] = "Basic " + ["admin:smartvm"].pack("m0") if login
  headers["X-Auth-Token"]  = @auth_token                             if @auth_token

  response = http.send(type, uri.path, *[payload, headers].compact)
  puts response
  JSON.parse(response.body)
end

Net::HTTP.start(@api_route.host, @api_route.port) do |api|
  # Login
  login      = api_request(api, login: true)
  @auth_token = login["auth_token"]

  # Fetch Settings
  response = api_request(api)
  puts response["api"]

  # Update Settings
  api_request(api, type: "patch", payload: {:api => {:authentication_timeout => "1337.minutes"}}.to_json)

  # Fetch updated Settings
  response = api_request(api)
  puts response["api"]
end
```

Are we expecting to do what @skateman suggested [here](https://github.com/ManageIQ/manageiq-api/issues/920#issuecomment-709783687)?

> ... The best would be to allow POST to `arbitrary_resource_paths`, i.e. URLs like `/api/zones/:id/settings/authentication/amazon_key` to edit just the specific field.

Or are we content with what already exists?

**Comment by Fryguy** [comment]
I think we can change this issue into an RFE for the ability to POST to arbitrary_resource_paths.  It's really up to @skateman if he wants to use the existing mechanism on the UI side first, or to wait until the POST to arbitrary_resource_paths feature is added.

**Comment by skateman** [comment]
> I think we can change this issue into an RFE for the ability to POST to arbitrary_resource_paths. It's really up to @skateman if he wants to use the existing mechanism on the UI side first, or to wait until the POST to arbitrary_resource_paths feature is added.

PUT/PATCH (I guess) :wink:

**Comment by NickLaMuro** [comment]
So, checking back in with this one to make sure I wasn't holding anything up, I am going to push back on the RFE that has been requested and say we shouldn't support `"arbitrary_resource_paths`", since we don't know how many levels deep it could be:

https://github.com/ManageIQ/manageiq/blob/7ea2845fc/config/settings.yml#L24-L41

And I would rather not expose a potential security vulnerability or break REST conventions to support this feature.

cc @abellotti

**Comment by skateman** [comment]
Fair enough, closing...
