### ISSUE TITLE
Querying for providers that suport the creation of flavors

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#924]
Is there a way to get a list of EMSes that support the creation of Flavors? In our UI controller it's solved via:
```ruby
    ems_list = Rbac::Filterer.filtered(ManageIQ::Providers::CloudManager).select do |ems|
      ems.class::Flavor.supports?(:create) if ems.class.constants.include?(:Flavor)
    end
```

@miq-bot add_label question
@miq-bot assign @gtanzillo

**Comment by Fryguy** [comment]
If the pattern where you can do an OPTIONS query on an ems is not sufficient, then we should enhance that.  Alternatively I could see an OPTIONS query on flavors, but then you'd need a way to know what kind of EMS that flavor belongs to.  cc @agrare

**Comment by agrare** [comment]
Yeah `supports :create` on the Flavor class works but you have to find the subclass first.  `Flavor.class_by_ems` works when you are looking at a single ems.
@skateman would a `supports_create_flavor?` feature work for you?

**Comment by skateman** [comment]
Yeah, if there would be an API request on the providers with a filter that returns all these, I'm good with it :+1:

**Comment by skateman** [comment]
Closing in favor of https://github.com/ManageIQ/manageiq/pull/20747
