### ISSUE TITLE
Invalidating product feature caches when creating a child (ops) tenant

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#928]
There's an explicit call to `/ops/invalidate_miq_product_feature_caches` when creating a new child tenant that runs `MiqProductFeature.invalidate_caches`. This is the only single endpoint that is not API-driven for this form.

I am wondering if it would be possible to either have a dedicated endpoint for this in the API, or to call this any time a new feature is called.

@miq-bot add_label question
@miq-bot assign @gtanzillo

**Comment by Fryguy** [comment]
Why does the UI do this?  Feels more like a backend concern, IMO, in a similar way we have to invalidate the Settings cache when a setting changes.
