### ISSUE TITLE
Endpoint for Policy simulation

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-api#936]
The policy simulation itself is an asynchronous task initiated by [`.rsop_async`](https://github.com/ManageIQ/manageiq/blob/master/app/models/mixins/miq_policy_mixin.rb#L141) from the UI controller. 

![Screenshot from 2020-10-22 13-14-30](https://user-images.githubusercontent.com/649130/96864351-8a0a0980-1468-11eb-9586-73a1b9ca4e7c.png)

The VM selection filelds in the form can be probably feeded using existing endpoints. The event selection is however, just partially available, there's no endpoint to retrieve the `MiqEventDefinitionSet`, only the underlying `MiqEventDefinition` entities.

@miq-bot add_label help wanted
@miq-bot assign @gtanzillo

**Comment by skateman** [comment]
The `/api/event_definition_sets` endpoint seems okay to me. Now we would need an endpoint that implements `MiqPolicyMixin#rsop_async`, I think the best location would be `POST /api/event_definition/:id` with a `simulate` action, but @abellotti should confirm. cc @gtanzillo

**Comment by abellotti** [comment]
You meant event_definition_sets ? If so, that makes sense,  resource endpoint **POST /api/event_definition_sets/:id** with action "**simulate**"

**Comment by skateman** [comment]
The PR @lfu created is for listing `event_definition_sets` but the next step in the policy simulation is to select an actual `event_definition` and run the simulation against it.

**Comment by abellotti** [comment]
Ahh ok, so for MiqEventDefinition that is currently exposed via /api/events, so sounds like that would be a **POST /api/events/:id** action simulate instead

**Comment by skateman** [comment]
> Ahh ok, so for MiqEventDefinition that is currently exposed via /api/events, so sounds like that would be a **POST /api/events/:id** action simulate instead

I'm good with that, so @lfu we need a `simulate` action under `/api/events/:id` with basically the same behavior as `rsop_async` but returning the task ID as any other async API request would do.

**Comment by lfu** [comment]
`MiqPolicyMixin` is included by many objects that support policy. `MiqPolicyMixin#rsop_async` is a class method of the event targets. So it seems not right to have a `simulate` action for the events.

In my opinion, `simulate` action should be added for those objects that support policy, like `Vm`, `ExtManagementSystem`, `Host` etc. There are about 15 classes that could call `MiqPolicyMixin#rsop_async`.

Is there a way to define a shared action once for all?

**Comment by abellotti** [comment]
We have many resources that support the "resolve" action, see subcollection/policies.rb -> policy_resolve, essentially triggering RSOP's.  is that what is needed here ?

**Comment by lfu** [comment]
`resolve` action points to `policy_resolve` that calls an instance method in `MiqPolicyMixin`. But `MiqPolicyMixin#rsop_async` is a class method that we have to add in.

**Comment by skateman** [comment]
Well, if you look at the screenshot above, you can only select VMs (1+) against one (1) event, so I still think that the best is to keep it under events cc @Fryguy

**Comment by Fryguy** [comment]
From a user's standpoint, would I expect to "go to an event and ask it to be simulated on a given resource", or "go to a resource and ask for a simulation based on the given event"?

IMO, more people would think the latter would be more intuitive, so by extension I think the resource (e.g. a VM) should have a simulate_policy action where you give it which event to start the simulation with.

**Comment by skateman** [comment]
> From a user's standpoint, would I expect to "go to an event and ask it to be simulated on a given resource", or "go to a resource and ask for a simulation based on the given event"?
> 
> IMO, more people would think the latter would be more intuitive, so by extension I think the resource (e.g. a VM) should have a simulate_policy action where you give it which event to start the simulation with.

But what if the user simulates against multiple VMs (which is the case above on the screenshot)?

**Comment by Fryguy** [comment]
Bulk action?

**Comment by Fryguy** [comment]
Actually...where in the screenshot do they simulate against multiple VMs?  I don't even see a selection, unless that first box is choosing all Cloud/Infra VMs?

**Comment by Fryguy** [comment]
FWIW, I've always found that form confusing precisely because it's backwards...you simulate policy on a resource and you kick the policy with an event.  The fact that you pick the event first is just weird to me.

**Comment by skateman** [comment]
> Bulk action?

I'm not so sure, then we're putting more work on the frontend, because it has to figure out which VMs to simulate against. 
![Screenshot from 2021-01-27 07-26-15](https://user-images.githubusercontent.com/649130/105951857-f81a2a00-6070-11eb-8b41-d28595899c6a.png)

We only have the ID of the VM on the frontend if the user selects the *Single VM/Instance* option and simulates against a single VM. Any other combination of form values would not have any available VM ids in the form state. For a bulk query we would have to send an API request to figure out what VMs are under the selected cluster/provider/host and IMO this is kinda ineffective.

Whereas if we submit a regular query against an event to simulate, we pass an entity type + id, the backend can just simply query the list of VMs under that entity. There are no additional server roundtrips before the actual form submission...

**Comment by skateman** [comment]
There is a different kind of policy simulation that is accessible from the GTL view of VMs or other entities where the bulk query would make sense, but there you can select multiple policy profiles (not events) and simulate them on multiple entities which you select with checkboxes, i.e. you know their IDs and there's no need for a server rountrip.

**Comment by lfu** [comment]
[PolicyMixin.rsop_aync](https://github.com/ManageIQ/manageiq/blob/ae1b5cacb3ac65b0317fd353a11e1f217870b291/app/models/mixins/miq_policy_mixin.rb#L141) could work for `VM`, `Host`, `ContainerImage` and many other objects. 
Do we plan to add `simulate` action for all of them or just `VM`?

**Comment by Fryguy** [comment]
After our discussion the comment is over in the PR here: https://github.com/ManageIQ/manageiq-api/pull/993#issuecomment-768410903

**Comment by Fryguy** [comment]
Closed via #993
