### ISSUE TITLE
Metric Rollups API filtering based on parameter not working as expected

### ISSUE THREAD

**Issue by sonalkakode** [ManageIQ/manageiq-api#956]
Issue Summary

Two parameters "end_date" and "resource_ids" in the Metric Rollups API do not provided response as expected with CP4MCM 2.1 build.

Issue Details

1.) When using end_date parameter in "api/metric_rollups" , even though end_date is provided , we are getting response above that timestamp.
API used : "https://inframgmtinstall-cp4mcm-customer3.multicloud-ibm.com/api/metric_rollups?expand=resources&resource_type=VmOrTemplate&capture_interval=daily&start_date='2020-10-21'&end_date='2020-10-22'&sort_by=timestamp&sort_order=desc"  

Tried above query for dates without quotes as well.Still the same response.

https://inframgmtinstall-cp4mcm-customer3.multicloud-ibm.com/api/metric_rollups?expand=resources&resource_type=VmOrTemplate&capture_interval=daily&start_date=2020-10-21&end_date=2020-10-22&sort_by=timestamp&sort_order=desc

![end_date_issue](https://user-images.githubusercontent.com/17743846/97830086-dcadb600-1cf1-11eb-8c17-64536a1a2386.png)

2.) When using resource_ids parameter in "api/metric_rollups" , no results are achieved even though the resource exists.
API used : "https://inframgmtinstall-cp4mcm-customer3.multicloud-ibm.com/api/metric_rollups?expand=resources&resource_ids=[1011]&resource_type=VmOrTemplate&capture_interval=daily&start_date='2020-10-21'&end_date='2020-10-22'&sort_by=timestamp&sort_order=desc"
NOTE : Resource id from #1 Screenshot has been considered for filtering.
![resource_ids_issue](https://user-images.githubusercontent.com/17743846/97830098-e8997800-1cf1-11eb-8b93-bf565c777eaa.png)

We have tried these similar APIs on standalone CF server and same issue has been observed.

Environment Details

CP4MCM --> https://cp4mcm-customer3.multicloud-ibm.com
CF URL = https://inframgmtinstall-cp4mcm-customer3.multicloud-ibm.com/
Credentials : Please contact Aniruddha Navare(vareanan@in.ibm.com)

Step to Reproduce
1.) Login to CF URL using REST APIs.
2.) Hit the URLs mentioned above and View the response.

Response json attached:
[response.zip](https://github.com/ManageIQ/manageiq-api/files/5472818/response.zip)

**Comment by sonalkakode** [comment]
Downstream issue created : https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/14787

**Comment by Fryguy** [comment]
@abellotti @gtanzillo Can you take a look at this one?

**Comment by abellotti** [comment]
@lpichler signature for end_date seems correct as per https://www.manageiq.org/docs/reference/latest/api/reference/metric_rollups.html.    I don't think we're looking at end_date here https://github.com/ManageIQ/manageiq-api/blob/6096543dcfce5dd1ca1f6a8582cb7c834678a877/lib/services/api/metric_rollups_service.rb#L9 because the slice does not include it.    Also, we should be adding a spec that tests the end_date.

**Comment by sonalkakode** [comment]
@lpichler , Does this PR also fix the **resource_ids** parameter issue I mentioned above?

**Comment by lpichler** [comment]
@sonalkakode 

It was working before and I see improper signature in https://www.manageiq.org/docs/reference/latest/api/reference/metric_rollups.html

If you need to filter by `resource_ids` you have to do 
`resource_ids[]=1&resource_ids[]=2&resource_ids[]=4`
instead if `resource_ids=[1,2,3]` as it is in doc.

then in your example:

```
/api/metric_rollups?expand=resources&resource_ids[]=1011&resource_type=VmOrTemplate&capture_interval=daily&start_date='2020-10-21'&end_date='2020-10-22'&sort_by=timestamp&sort_order=desc
```

Note: Be aware that request parameter `resource_ids` is `MetricRollup#resource_id`(id of VM for example) and not `MetricRollup#id`.

Let me know if you have any other questions.

thanks
