### ISSUE TITLE
Investigate performance issues with REST API

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/manageiq-api#96]
Note: This is reported by Loic

- Logging is pretty slow, there is a top progress bar that is providing some information… We should look at some animation at the centre of the page to be more informative..
- More I am using the UI faster it seems to be.. this is may be an impression…
- Clicking on My Service is the slowest thing.. changing page in My Service is also Slow
- Once the UI was completely stuck… I cannot click to anything for few seconds.. .I think the previous video capture this moment.
- I looked at “time_taken” in the log, which seems to be what we need to look at .. I am not sure what is acceptable time… I see some some valid above 1 second (2-3), below 1 seconds and below 0,1 seconds.. 
- My impression by watching logs at the same time I am waiting is the UI is: there are multiple API Calls for some requests and then some processing on the UI side.

**Comment by chriskacerguis** [comment]
Here are some of my thoughts on the matter:

> More I am using the UI faster it seems to be.. this is may be an impression…

This is likely true.  As you use the SUI, things get cached (both browser) and (I'm guessing) in the DB.

> Clicking on My Service is the slowest thing.. changing page in My Service is also Slow

This pages does a LOT of calls because we have to do a lot of look ups.  Tracking back to our meeting today, per what Jason said perhaps we can look at returning more data in the calls vs. having to do calls to get various data.  That said, I'm not 100% sure we will get anything from one big REST call vs. multiple smaller REST calls = One big DB query vs. multiple little queries.  I have not looked at the back end at all, but I'd be surprised if it makes a massive difference.


All that said, part of using REST is the ability to do lots of look ups.  The best thing would be to profile each call, and turn the performance team loose on them.

**Comment by imtayadeway** [comment]
@chriskacerguis can you identify what conditions would need to be met in order for us to close this issue? It seems open-ended - perhaps (if this is intended to attract discussion around these issues) either a talk article or perhaps open smaller, more actionable issues?

**Comment by imtayadeway** [comment]
Closing this in favor of the more actionable/specific https://github.com/ManageIQ/manageiq-api/issues/146. We can always open more issues along those lines with specific, actionable items in the future if necessary.
